### ISSUE TITLE
Remove the 'zarf-' prefix from Helm ReleaseName deployments as this modifies the zarf.yaml's ReleaseName spec (or make optional)

### ISSUE THREAD

**Issue by davesee** [defenseunicorns/zarf#1020]
### Environment
Device and OS: Win11 / WSL / Ubuntu 22
App version: v0.22.2
Kubernetes distro being used: Kind

### Steps to reproduce
1. Deploy a helm chart/release with the releaseName defined
2. Some resources are deployed with a `zarf-` prefix
3. Resources that reference the release fail (Grafana DataSource for example)
    - Yes, the prefix can be added, but when deploying to multiple targets (Flux and Zarf) then everything needs to be edited on a per resource basis for Zarf releases

e.g. using Prometheus kube-prometheus-stack helm chart:
- https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack

This deployment results in some releases/resources with the `zarf-` prefix and others without.

```yaml
kind: ZarfPackageConfig
metadata:
  name: prometheus-ksm
  description: "Deploys the base prometheus-ksm helm chart"
components:
  - name: prometheus-ksm
    required: true
    charts:
      - name: kube-prometheus-stack
        releaseName: prometheus-ksm
        url: https://prometheus-community.github.io/helm-charts
        version: 41.7.0
        namespace: prometheus
    images:
      - quay.io/prometheus/alertmanager:v0.24.0
      - k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.3.0
      - quay.io/prometheus-operator/prometheus-operator:v0.60.1
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.60.1
      - quay.io/thanos/thanos:v0.28.1
      - quay.io/prometheus/prometheus:v2.39.1
      - quay.io/kiwigrid/k8s-sidecar:1.19.2
      - grafana/grafana:9.2.2
      - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.6.0
      - quay.io/prometheus/node-exporter:v1.3.1
```

### Expected result
It is expected to create resources with the releaseName of `prometheus-ksm` as specified in the `zarf.yaml` file.

### Actual Result
Relevant resources created:
```bash
$ kubectl get all -n prometheus | awk '{print $1}'

Pods
pod/alertmanager-zarf-prometheus-ksm-kube-p-alertmanager-0
pod/prometheus-zarf-prometheus-ksm-kube-p-prometheus-0
pod/zarf-prometheus-ksm-grafana-9d9bb7bfb-jnd27
pod/zarf-prometheus-ksm-kube-p-operator-6fc5887d9-tqnbf
pod/zarf-prometheus-ksm-kube-state-metrics-77dfc698dd-7g7jq
pod/zarf-prometheus-ksm-prometheus-node-exporter-c2j2f

Services
service/alertmanager-operated
service/prometheus-operated
service/zarf-prometheus-ksm-grafana
service/zarf-prometheus-ksm-kube-p-alertmanager
service/zarf-prometheus-ksm-kube-p-operator
service/zarf-prometheus-ksm-kube-p-prometheus
service/zarf-prometheus-ksm-kube-state-metrics
service/zarf-prometheus-ksm-prometheus-node-exporter

Stateful Sets
statefulset.apps/alertmanager-zarf-prometheus-ksm-kube-p-alertmanager
statefulset.apps/prometheus-zarf-prometheus-ksm-kube-p-prometheus
```

### Visual Proof (screenshots, videos, text, etc)
![image](https://user-images.githubusercontent.com/68443470/202521140-6ec2c3e2-5f15-4919-8e96-85443810ca26.png)
![image](https://user-images.githubusercontent.com/68443470/202520908-d99497b3-e139-4b3d-9de0-a3403cd9bfa7.png)
![image](https://user-images.githubusercontent.com/68443470/202520981-9c3e099a-6fd2-48a7-9d81-f2d6588fe649.png)
![image](https://user-images.githubusercontent.com/68443470/202521047-3754ed64-5c88-4d96-9f1f-b8c43d84b68e.png)
![image](https://user-images.githubusercontent.com/68443470/202521181-38408a99-52db-45b1-862b-ecc88106a119.png)

### Severity/Priority

Medium

### Additional Context

When deploying a large number of resources which need to integrate by names (ConfigMaps, ServiceMonitors etc) then the overhead becomes high. 

I would assume there are many deployments which hard-code the `zarf-` prefix, so we can either:
- Have an option to `opt-out` of the prefix `releaseNameZarfPrefix: false`  or
- remove the prefix and provide and option to include the `releaseNamePrefix: string` 

or
- Remove the prefix entirely

Relevant code: 
- https://github.com/defenseunicorns/zarf/blob/main/src/internal/helm/chart.go#L46
- https://github.com/defenseunicorns/zarf/blob/main/src/internal/helm/chart.go#L145
