### ISSUE TITLE
Support remote files in zarf.yaml manifests

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#1056]
**Is your feature request related to a problem? Please describe.**
In the same vein as https://github.com/defenseunicorns/zarf/issues/1055, I want to ensure that when a Zarf package is being built, it's using the files that are checked into VCS, not on the user's local machine.

**Describe the solution you'd like**
Consider the following `zarf.yaml`:
```
kind: ZarfPackageConfig
metadata:
  name: test
components:
  - name: upgrade-test
    required: true
    namespace: podinfo
    images:
      - ghcr.io/stefanprodan/podinfo:6.2.3
    repos:
      - https://github.com/UncleGedd/zarf-playground
      - https://github.com/stefanprodan/podinfo
    charts:
      - path-to-chart
    manifests:
      - name: podinfo
        namespace: podinfo
        files: 
            - https://github.com/UncleGedd/zarf-playground/blob/main/upgrade-testing/zarf.yaml # this is a remote file!
```
I'd like the `...manifest.files` to support remote files
