### ISSUE TITLE
Import Component from OCI Registry

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1138]
**Is your feature request related to a problem? Please describe.**
When building a Zarf package from components defined in another Zarf file, I don't want to have to have those components zarf.yaml local.  I'd like to be able to piece together pre-build zarf packages from a registry:

```yaml
kind: ZarfPackageConfig
metadata:
  name: demo
  description: 'reference component from another OCI Zartifact'

components:
 - name: iac
   import:
     url: oci://zarf.dev/defenseunicorns/aws-iac:v0.1
     name: iac
 - name: bigbang
    import:
      url: oci://zarf.dev/bigbang/bigbang:1.49.0
 - name: podinfo
    import:
      url: oci://zarf.dev/defenseunicorns/podinfo:6.1.3
```
