### ISSUE TITLE
tf-controller for IaC

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/zarf#1140]
Problem:
Terraform is scoped to only provide a mechanism to provision / update IaC but inherently relies on 3rd party tooling / additional implementation details for GitOps, state management and drift detection. Zarf has the potential to provide an opinionated way to use terraform in a way that addresses these concerns.

Potential Solution:
Weaveworks has a [tf-controller](https://github.com/weaveworks/tf-controller) which 1.) maintains state within k8s by default (read discoverability for BB), 2.) has a GitOps workflow for terraform and 3.) leverages the powers of k8s for drift detection / correction. I propose we look at this or comparable tooling that maintains state in k8s by default and we can do state backup to a more robust storage mechanism.

If we go with the tf-controller, I expect it would behave similar to the bb helm chart [issue](https://github.com/defenseunicorns/zarf/issues/1092) which leverages the flux=true flag.

Alternatives:
External workflows / tooling (pipelines, processes or tooling like atlantis, crossplane, etc.) that compensate for native terraform deficiencies. 

Here is an [example](https://github.com/defenseunicorns/iac/blob/main/zarf.yaml) of using zarf in it's current state to gitops IaC with limitations on k8s discovery of terraform provisioned resources and no drift detection. 

parent issue #939

**Comment by mikevanhemert** [comment]
I am new to the experimental Weaveworks tf-controller and recognize most of my questions are coming out of ignorance. What are the chicken-and-egg considerations if this became the recommended path forward for managing IaC with Zarf?

How would Zarf provision an EKS cluster with Terraform and maintain its state if the tf-controller is used? Is the assumption that a `k3s` or similar 'jumpbox' cluster needs to be used? If this is the case, could the Terraform state for EKS be migrated into EKS so that the external cluster doesn't need to hang around?

I am interested in an alternative where Terraform state is managed locally and then persisted in / retrieved from a Zarf-managed cluster. Assuming Zarf afforded a generic `key:value` store, I think we could load Terraform state and even provide for locking / unlocking on subsequent IaC component deploys.

Assuming a Zarf package with these components:
```yaml
components:
  - name: download-dependencies
  - name: terraform
      scripts:
        before:
          # terraform init
          # read terraform state (if it exists in Zarf's `key:value` store
          # terraform apply
        after:
          # save terraform state in Zarf's `key:value` store
  - name: init
  - name: flux
  - name: big-bang
  - name: mission-app
```

The workflow with my suggested `key:value` store, assuming no infrastructure exists, following a `zarf package deploy`:
1. provision resources in AWS, including EKS, save terraform state in the cluster 
2. zarf init!
3. Install flux
4. Install Big Bang
5: Install that mission app

The same workflow assuming an innocuous change to the underlying Terraform (new security group entry, for instance)
1. read terraform state, apply the change, save the updated state in the cluster
2. skip zarf init because there's magic logic this example isn't going into
3. helm install flux (already there, no changes)
4. flux install big-bang components (no changes)
5. flux install the mission app (no changes)

The highlight here is by opening Zarf up to manage a `key:value` store I believe we can successfully store and manage terraform state and other component-to-component data sharing. I added related but unique thoughts here as well #1137
