### ISSUE TITLE
Error when referencing OCI helm charts under component images

### ISSUE THREAD

**Issue by lsoica** [defenseunicorns/zarf#1244]
### Steps to reproduce
1. In zarf.yaml, define an OCI helm chart under component images:
```
kind: ZarfPackageConfig
components:
  - name: service
    description: "Description"
    required: true
    images:
      - <OCI registry>/demo:0.1.0
```
2. Create the package
```
zarf package create --confirm
```
3. The following error is reported
```
     ERROR:  Failed to create package: unable to pull images after 3 attempts: failed to write image tarball:               
             mismatched fs layers (1) and diff ids (0)
```

### Expected result
Include the helm chart image as any other OCI registry image.

### Additional Context
Helm pull on the same image with helm required syntax is successful
```
helm pull oci://<OCI registry>/demo --version 0.1.0
```
