### ISSUE TITLE
Allow Zarf Variable to be the contents of a file

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1372]
### Is your feature request related to a problem? Please describe.
Some deploy time configurations naturally live as files:  TLS certs, credentials, etc.  it would be easier to be able to point to files on disk than need to move them into the zarf.toml file and risk formatting them incorrectly. 

e.g. for a BigBang deployment:

```yaml
istio:
  gateways:
    public:
      tls:
        key: ###ZARF_VAR_TLS_KEY_CONTENTS###
        cert: ###ZARF_VAR_TLS_CERT_CONTENTS###
```

There could be a new property in the variable definition that specifies it as a filepath location and not a literal:

```yaml
variables:
  - name: TLS_KEY_CONTENTS
    default: "privkey.pem"
    prompt: false
    type: file # defaults to literal
  - name: TLS_CERT_CONTENTS
    default: "fullchain.pem"
    prompt: false
    type: file # defaults to literal
```

This could be tackled with the actions (see below), but seems more complicated for a package dev for repeatedly using file contents as variables.

```
variables:
  - name: TLS_KEY_FILE
    default: "privkey.pem"
    prompt: false
  - name: TLS_CERT_FILE
    default: "fullchain.pem"
    prompt: false
components:
- actions:
    onDeploy:
      before:
      - cmd: cat "###ZARF_VAR_TLS_KEY###"
        setVariable: TLS_KEY_CONTENTS
      - cmd: cat "###ZARF_VAR_TLS_CERT###"
        setVariable: TLS_CERT_CONTENTS
```

which could now be used as above to contain the contents of the filename provided
