### ISSUE TITLE
Zarf attempts to resolve encoded characters in urls

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#1375]
### Environment
Device and OS: ubuntu 22 amd64
App version: 
Kubernetes distro being used: 0.24.2

### Steps to reproduce

```
- name: example url
  required: true
  files:
    - source: https://github.com/rancher/rke2/releases/download/v1.26.1%2Brke2r1/rke2.linux-amd64.tar.gz
      target: /some/location/
```
1. Create zarf.yaml with above component
2. build package

### Expected result

```
  ✔  Downloading https://github.com/rancher/rke2/releases/download/v1.26.1%2Brke2r1/rke2.linux-amd64.tar.gz
```

### Actual Result

```
  ✔  Downloading https://github.com/rancher/rke2/releases/download/v1.26.1%!B(MISSING)rke2r1/rke2.linux-amd64.tar.gz
```

### Severity/Priority

Low visual only
