### ISSUE TITLE
Image pull logs total / downloaded instead of downloaded / total GBs

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#1439]
### Environment
Device and OS: System76 Darter Pro, Pop!_OS 22.04 LTS
App version: v0.25.0-rc2
Kubernetes distro being used: k3d
Other

### Steps to reproduce
<details>
<summary>zarf.yaml</summary>

```yaml
kind: ZarfPackageConfig
metadata:
  name: demo
  description: "demo"
  architecture: amd64

components:
  - name: so-many-images
    description: "This think can fit so many images"
    required: true

    images:
      - "registry1.dso.mil/ironbank/big-bang/base:2.0.0"
      - "registry1.dso.mil/ironbank/opensource/istio/pilot:1.16.1"
      - "registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.16.1"
      - "registry1.dso.mil/ironbank/opensource/istio/install-cni:1.16.1"
      - "registry1.dso.mil/ironbank/tetrate/istio/istioctl:1.15.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.15.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/tetrate/istio/pilot:1.15.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/tetrate/istio/install-cni:1.15.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/opensource/istio/operator:1.16.1"
      - "registry1.dso.mil/ironbank/tetrate/istio/operator:1.15.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/opensource/ingress-nginx/kube-webhook-certgen:v1.3.0"
      - "registry1.dso.mil/ironbank/opensource/jaegertracing/all-in-one:1.39.0"
      - "registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-operator:1.39.0"
      - "registry1.dso.mil/ironbank/opensource/kiali/kiali-operator:v1.60.0"
      - "registry1.dso.mil/ironbank/opensource/kiali/kiali:v1.60.0"
      - "registry1.dso.mil/ironbank/bigbang/cluster-auditor/opa-exporter:v0.0.7"
      - "registry1.dso.mil/ironbank/opensource/kubernetes/kubectl:v1.25.3"
      - "registry1.dso.mil/ironbank/opensource/openpolicyagent/gatekeeper:v3.10.0"
      - "registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:8.5.2"
      - "registry1.dso.mil/ironbank/elastic/kibana/kibana:8.5.2"
      - "registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:2.5.0"
      - "registry1.dso.mil/ironbank/opensource/fluent/fluent-bit:2.0.6"
      - "registry1.dso.mil/ironbank/big-bang/grafana/grafana-plugins:9.3.2"
      - "registry1.dso.mil/ironbank/kiwigrid/k8s-sidecar:1.21.0"
      - "registry1.dso.mil/ironbank/opensource/kubernetes/kube-state-metrics:v2.7.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-config-reloader:v0.61.1"
      - "registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-operator:v0.61.1"
      - "registry1.dso.mil/ironbank/opensource/prometheus/alertmanager:v0.24.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus/node-exporter:v1.5.0"
      - "registry1.dso.mil/ironbank/opensource/prometheus/prometheus:v2.40.5"
      - "registry1.dso.mil/ironbank/twistlock/console/console:22.06.197"
      - "registry1.dso.mil/ironbank/twistlock/defender/defender:22.06.197"
      - "registry1.dso.mil/ironbank/opensource/kubernetes-sigs/metrics-server:v0.6.2"
      - "registry1.dso.mil/ironbank/neuvector/neuvector/controller:5.0.2"
      - "registry1.dso.mil/ironbank/neuvector/neuvector/enforcer:5.0.2"
      - "registry1.dso.mil/ironbank/neuvector/neuvector/manager:5.0.2"
      - "registry1.dso.mil/ironbank/neuvector/neuvector/scanner:latest"
      - "registry1.dso.mil/ironbank/opensource/bitnami/elasticsearch-exporter:1.5.0-debian-11-r17"
```
</details>

1. Create the Zarf package defined above
    ```bash
    zarf package create --confirm
    ```

### Expected result
In the `Pulling x images (y GBs of z GBs)` message y should be the number of GBs pulled so far, z should be the total number of GBs

### Actual Result
In the `Pulling x images (y GBs of z GBs)` message y is the total number of GBs, z the number of GBs pulled so far

### Visual Proof (screenshots, videos, text, etc)
![image](https://user-images.githubusercontent.com/108541208/225489648-98ee2921-52c8-435f-b5a8-f768e25b90e7.png)

### Severity/Priority
Low
