### ISSUE TITLE
Zarf Terraform Module Discovery and Use

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1482]
### Is your feature request related to a problem? Please describe.

When trying to use Terraform with Zarf, copying external modules seems difficult.  The modules refrenced are external git repositories that need to be overlayed into a particular folder, e.g. `.terraform/modules/<name of module in my terraform>/modules/<name of upstream module>`.  There are a couple improvements desired:

1. Automatic Discovery of the modules needed.  There happens to be a terraform native object at`.terraform/modules/modules.json` once a terraform project has been `terraform init`ed.  This file contains the exact data that is needed for collecting resources:

```bash
$ cat .terraform/modules/modules.json | jq .
{
  "Modules": [
    {
      "Key": "",
      "Source": "",
      "Dir": "."
    },
    {
      "Key": "S3",
      "Source": "git::https://github.com/defenseunicorns/iac.git//modules/s3-irsa?ref=s3_output_role_arn",
      "Dir": ".terraform/modules/S3/modules/s3-irsa"
    },
    {
      "Key": "S3.s3_bucket",
      "Source": "registry.terraform.io/terraform-aws-modules/s3-bucket/aws",
      "Version": "3.6.0",
      "Dir": ".terraform/modules/S3.s3_bucket"
    }
  ]
}
```
 In our terraform, I use the module as defined here:

```hcl
module "S3" {
    source = "github.com/defenseunicorns/iac//modules/s3-irsa?ref=s3_output_role_arn"
    name_prefix = "${var.name}"
    eks_oidc_provider_arn = "${var.eks_oidc_provider_arn}"
    kms_key_alias = "${var.name}"
    kubernetes_service_account = "logging-loki"
    kubernetes_namespace = "logging"
    dynamodb_enabled = "false"
}
```

The file correctly identifies the name of my module and the source that it should be pulled from.  Not only that, but it sees the module we call also has a dependency module that the `s3-irsa` module uses. This suggests that there's existing terrraform code to do the analysis that we need to identify the modules and where they should be saved on disk for deployment.

2. Given this list of modules and locations they should go, I'm not sure how to use the `repo` noun in zarf to lay those git modules in the correct location.

### Describe the solution you'd like

In an ideal world, there's a clean interface (like a `terraform` noun) that would be able to capture this logic inside of Zarf or a zarf extension

```yaml
components:
- name: s3
  extensions:
    terraform:
      backend:
        s3: <bucketName>
      # local: <directory> # for local tf state file
      module:
        path: ./s3 # path to my local terraform module
      variables: #injects into the tf vars
        aws_region: ###ZARF_VAR_AWS_REGION###
        cluster_name: ####ZARF_VAR_CLUSTER_NAME####
```

This noun would:
* Identify and collect all the providers
* Identify and collect all the modules
* Write the providers and modules in the correct location
* Configure the backend provider during deploy
* configures the variables in a cleaner manner
* Manage the correct logic for init/apply/deploy/remove for a consistent feel
* Creates a ZARF_VAR for each output of the form ###ZARF_VAR_TERRAFORM_<MODULE_NAME>_<OUTPUT>###

### Describe alternatives you've considered
Actions.  Can probably get it to work, but it feels complicated and without a central definition, there are going to be slight different implementations for every package

### Additional context

My current Terraform section of my zarf.yaml

```yaml
components:
  - name: download-terraform
    required: true
    actions:
      onDeploy:
        after:
          - cmd: rm -f terraform || true
            description: Clean up previous install since archiver doesn't overwrite the output
          - cmd: rm -rf run/s3/tf-plugins/registry.terraform.io/hashicorp/aws/###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###/darwin_arm64 || true
          - cmd: ./zarf tools archiver decompress tmp/terraform_###ZARF_PKG_VAR_TERRAFORM_VERSION###_darwin_arm64.zip .
          - cmd: ./zarf tools archiver decompress tmp/terraform-provider-aws_###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###_darwin_arm64.zip run/s3/tf-plugins/registry.terraform.io/hashicorp/aws/###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###/darwin_arm64
          - cmd: rm -rf tmp
    files:
      # mac m1 terraform aws provider binary
      - source: https://releases.hashicorp.com/terraform-provider-aws/###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###/terraform-provider-aws_###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###_darwin_arm64.zip
        target: tmp/terraform-provider-aws_###ZARF_PKG_VAR_TERRAFORM_PROVIDER_AWS_VERSION###_darwin_arm64.zip
      # mac m1 terraform binary
      - source: https://releases.hashicorp.com/terraform/###ZARF_PKG_VAR_TERRAFORM_VERSION###/terraform_###ZARF_PKG_VAR_TERRAFORM_VERSION###_darwin_arm64.zip
        target: tmp/terraform_###ZARF_PKG_VAR_TERRAFORM_VERSION###_darwin_arm64.zip
    # need to add the iac modules that are needed to be pulled in
 
  - name: s3-files
    required: true
    files:
    # terraform code
    - source: s3/main.tf
      target: run/s3/main.tf # save it into a different folder so we don't overwrite my local terraform
    - source: s3/terraform.tfvars
      target: run/s3/terraform.tfvars
  - name: execute-terraform
    required: true
    actions:
      onDeploy:
        before:
          - cmd: "terraform init -plugin-dir=tf-plugins"
            dir: run/s3
          - cmd: "terraform apply -auto-approve"
            dir: run/s3
      onRemove:
        before:
          - cmd: "terraform destroy -auto-approve"
            dir: run/s3
  - name: outputs
    required: true
    actions:
      onDeploy:
        after:
          - cmd: "terraform output -raw s3_bucket"
            dir: run/s3
            setVariable: LOKI_S3_BUCKET
          - cmd: "terraform output -raw aws_region"
            dir: run/s3
            setVariable: LOKI_S3_AWS_REGION
          - cmd: "terraform output -raw irsa_role"
            dir: run/s3
            setVariable: LOKI_S3_ROLE_ARN
```
