### ISSUE TITLE
Packaging issue: ImagePullBackOff

### ISSUE THREAD

**Issue by janluak** [defenseunicorns/zarf#1591]
Hey guys,

very nice tool, seems to help us out a lot!

Unfortunately, I cannot make a custom example work.

My setup is a ubuntu:22.10 vm without network. Install steps just like the docs and command `ip route add default via 0.0.0.0 metric 9999 dev eth0` run since k3s requires to have a default route...

The dos-games example work completely fine when packing on my machine and deploying on the vm. But the config attached leads to a `ImagePullBackOff ` error on the vm for the pods.

Is the config bad or am I missing a something here?

Thanks a lot!!

---

zarf.yaml:
```
metadata:
  name: a-nginx
  description: "Simple example with a nginx"

components:
  - name: baseline
    required: true
    manifests:
      - name: b-nginx
        namespace: default
        files:
          - manifest/deployment.yaml
    images:
      - nginx
```

deployment.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c-nginx-deployment
spec:
  selector:
    matchLabels:
      app: d-nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: d-nginx
    spec:
      containers:
      - name: e-nginx
        image: nginx
        ports:
        - containerPort: 80
```
