### ISSUE TITLE
Help with ingress (nginx)

### ISSUE THREAD

**Issue by janluak** [defenseunicorns/zarf#1625]
Hey guys,

I can't get my head around the docs for using helm charts:

Due to not having traefik running as ingress controller pre-shipped (I think it's standard for k3s for having it included but it's not part of zart's k3s), I wanted to install nginx-ingress.

There is an [installation guide](https://kubernetes.github.io/ingress-nginx/deploy/#quick-start) presenting this helm command:
```
helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace
```

I tried tons of ways to let zarf know to download the required images and deploy the helm config afterwards but always something is missing.

I guess I am just missing out a key concept for using helm... Could you please help and let me know how to deploy a standard helm?

Thanks a lot!

---
the zarf.yaml
```
kind: ZarfPackageConfig
metadata:
  name: nginx-ingress
  description: "ingress based on nginx"

components:
  - name: nginx-ingress
    required: true
    charts:
      - name: ingress-nginx
        namespace: ingress-nginx
        version: 4.6.0
        url: https://kubernetes.github.io/ingress-nginx
    images:
      - nginx/nginx-ingress:3.1.0
```

Alternatively, I followed the full nginx-ingress guide to have a full k8s config to run the nginx-ingress. See the darf.yaml here with correlating file [ingress-controller.yaml.txt](https://github.com/defenseunicorns/zarf/files/11273991/ingress-controller.yaml.txt):
```
kind: ZarfPackageConfig
metadata:
  name: nginx-ingress
  description: "nginx-ingress"

components:
  - name: nginx-ingress
    required: true
    manifests:
      - name: nginx-ingress
        namespace: nginx-ingress
        files:
          - manifest/ingress-controller.yaml
    images:
      - nginx/nginx-ingress:3.1.0

```

**Comment by Racer159** [comment]
Its not well documented but you should be able to turn back on traefik by specifying empty K3S_ARGS like this:

```
zarf init --set K3S_ARGS=""
```

You can see where that is pulled in here: https://github.com/defenseunicorns/zarf/blob/main/packages/distros/k3s/common/zarf.yaml#L8 (if it is not set it gets defaulted to `--disable traefik`)

---
That said, it looks like that is the wrong image for that chart.  This seemed to work for me:

```
# zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: nginx-ingress
  description: "ingress based on nginx"

components:
  - name: nginx-ingress
    required: true
    charts:
      - name: ingress-nginx
        namespace: ingress-nginx
        version: 4.6.0
        url: https://kubernetes.github.io/ingress-nginx
        valuesFiles:
          - "values.yaml"
    images:
      - registry.k8s.io/ingress-nginx/controller:v1.7.0
      - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
```

```
# values.yaml
controller:
  image:
    registry: registry.k8s.io
    image: ingress-nginx/controller
    tag: "v1.7.0"
    digest:
    digestChroot:
  admissionWebhooks:
    patch:
      enabled: true
      image:
        registry: registry.k8s.io
        image: ingress-nginx/kube-webhook-certgen
        tag: v20230312-helm-chart-4.5.2-28-g66a760794
        digest: 
```

I found the first image running `zarf prepare find-images`:

```
$ zarf prepare find-images .

Saving log file to /tmp/zarf-2023-04-19-09-56-32-1267556376.log

Using base directory .
components:
  ✔  Processing helm chart ingress-nginx:4.6.0 from repo https://kubernetes.github.io/ingress-nginx                         
  ✔  Templating helm chart ingress-nginx                                                                                    

  - name: nginx-ingress
    images:
      - registry.k8s.io/ingress-nginx/controller:v1.7.0
      - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
```

The second I found running `zarf tools monitor` (which launches `k9s`) and pressing `d` on the ImagePullBackOff error I saw then looking through the values file for it here: https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.6.0/charts/ingress-nginx/values.yaml (note I was on the tag for the 4.6.0 helm chart).

> **Note** I dropped the SHAs and overrode them using the `valuesFiles` key since Zarf currently will normalize all manifests to the OCI format and then push them to the remote - we have discussed ways to make it so that SHAs are kept in tact but that is still on our future roadmap.
