### ISSUE TITLE
Better messaging on Shallow `git` Clones

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1698]
### Is your feature request related to a problem? Please describe.
Shallow clones can cause issues with Zarf because it expects to mirror a repository and a shallow clone does not contain all of the object references in that repository.

### Describe the solution you'd like
Detect the `object not found` error on a git push in in the `push()` function (https://github.com/defenseunicorns/zarf/blob/182a4df40445f848cb47c0a7f52f10c982e10513/src/internal/packager/git/push.go#L157) and return an error that mentions shallow cloning:

```
return fmt.Errorf("unable to push the repo due to it being a shallow clone")
```

Additionally add a `:::caution` admonition to the [git-data example](https://docs.zarf.dev/examples/git-data) that describes that a user should not use shallow clones with Zarf linking them to a page like this for more information: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone

### Additional context
For more information see: https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1683743369646829

**Comment by dgershman** [comment]
Repro steps.

1. Init a new cluster with Zarf.
2. Build a package that uses a shallow git clone repo.

zarf.yaml
```yaml
kind: ZarfPackageConfig
metadata:
  name: shallow-clone
  version: v1.0.0
  description: "Failure testing a shallow clone git reference"

components:
  - name: shallow-nocode
    required: true
    repos:
      - file:///tmp/nocode
    actions:
      onCreate:
        before:
          - cmd: cd /tmp && rm -rf nocode && git clone --depth 1 https://github.com/kelseyhightower/nocode.git

```

Build the package command:
```shell
zarf package create --max-package-size=0 --confirm
```

3. Deploy the package to your initialized cluster.

```shell
zarf package deploy zarf-package-shallow-clone-amd64-v1.0.0.tar.zst --confirm
```

4. Observe error:

<img width="972" alt="Screenshot 2023-05-11 at 11 32 01 AM" src="https://github.com/defenseunicorns/zarf/assets/1850811/7b68a352-9e0b-43c8-9ece-e4fadedd8d26">
