### ISSUE TITLE
Reduce Verbosity to import multi-component Zarf package

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1711]
### Is your feature request related to a problem? Please describe.
When importing an entire Zarf package, each component needs to be identified and imported individually.   Currently it requires importing multiple components:

https://github.com/defenseunicorns/zarf-package-big-bang/blob/main/aws/zarf.yaml#L114-L126

### Describe the solution you'd like

- **Given** this [zarf package](https://github.com/defenseunicorns/zarf-package-big-bang/blob/main/defense-unicorns-distro/zarf.yaml)
- **When**creating a zarf package that uses this zarf package as "part" of it
- **Then** we could import the entire package at once:

```yaml
components:
...
- name: bigbang
  import:
    path: oci://ghcr.io/defenseunicorns/uds/bigbang:0.1.3
```

which would import all the components.

### Alternative

Something like this solution to performing a zarf init on the cluster:

https://github.com/runyontr/zarf-package-k3d/blob/main/zarf.yaml#L31-L39
