### ISSUE TITLE
Package create time relative path issues using imports

### ISSUE THREAD

**Issue by WeaponX314** [defenseunicorns/zarf#1756]
### Environment
Device and OS: Linux
App version: 0.27.0
Kubernetes distro being used: k3s, but really N/A here
Other: test works with 0.26.1

### Steps to reproduce
1. Look at attached tar.gz for complete working example that completes successfully on 0.26.1 but fails on 0.27.0
2. Copy this to some arbitrary directory and extract
3. Run zarf package create

### Expected result
1. Expect a package to be created

### Actual Result
Failed to create package: unable to compose component test-component: unable to get child component: unable to fix composed filepaths (see visual proof for more details)

### Visual Proof (screenshots, videos, text, etc)
0.26.1
``` 
[root@node1 ztest]# ./zarf_v0.26.1_Linux_amd64 package create --confirm

Using config file /root/ztest/zarf-config.toml

Saving log file to /tmp/zarf-2023-05-26-12-47-06-857083603.log

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

kind: ZarfPackageConfig
metadata:
  name: test-wrapper
  description: test outer wrapper
components:
- name: test-component
  required: true
  actions:
    onCreate:
      before:
      - cmd: tar czvf file.tar.gz -C "import" file.txt
        description: Process that ends up with a tar.gz
      after:
      - cmd: rm -rf file.tar.gz
        description: Cleans up
  files:
  - source: import/../file.tar.gz
    target: /tmp/remote_file.tar.gz
  ✔  Create Zarf package confirmed

                                                                                       
  📦 TEST-COMPONENT COMPONENT                                                          
                                                                                       

     file.txt                                                                                                                                                                                                                                                    
  ✔  Completed "Process that ends up with a tar.gz"                                                                                                                                                                                                              
  ✔  Completed "Cleans up"                                                                                                                                                                                                                                       
  ✔  Creating SBOMs for 0 images and 1 components with files.                                                                                                                                                                                                    
```
0.27.0
```                                                                                                                                                                                                 
[root@node1 ztest]# ./zarf_v0.27.0_Linux_amd64 package create --confirm

Using config file /root/ztest/zarf-config.toml

Saving log file to /tmp/zarf-2023-05-26-12-47-20-3120995904.log
     ERROR:  Failed to create package: unable to compose component test-component: unable to get child component:
             unable to fix composed filepaths: imported path import/###ZARF_PKG_TMPL_RELATIVE_DIR###/file.tar.gz
             does not exist
```


### Severity/Priority

### Additional Context
I know that this would work if I collapsed it into the wrapper. However, in the actual usage of this, we like to have a separate package created as well that doesn't include the other parts that get added to the outer wrapper that mainly imports. So this is a behavioral change and I am not certain if it is a bug or not but it also might be a teaching moment since maybe I am going about it wrong, please let me know if there is a better way. Bottom line, would like to have an imported zarf package create something that didn't previously exist and still have it be copied properly honoring any "before" actions that should take place before the files are looked at.

I have attached the setup for easy recreation.
[zarf_test.tar.gz](https://github.com/defenseunicorns/zarf/files/11578312/zarf_test.tar.gz)

**Comment by Noxsios** [comment]
You are correct @WeaponX314 . Before 0.27 you would have to use path hacking and variables (like your example) in order to use certain from imported components. In 0.27 this is no longer the case as `actions` and all imported resources are now properly relatively pathed from their source `zarf.yaml`. The following is how this behavior _should_ work:

```yaml
kind: ZarfPackageConfig
metadata:
  name: test-wrapper
  description: "test outer wrapper"

components:
  - name: test-component
    required: true
    import:
      path: import
      name: my-import-test
 ```
 
 and 
 
 ```yaml
kind: ZarfPackageConfig
metadata:
  name: test-pkg
  description: "test creating something before copy"

components:
  - name: my-import-test
    actions:
      onCreate:
        before:
          - cmd: tar czvf file.tar.gz file.txt
            description: Process that ends up with a tar.gz
        after:
          - cmd: rm -rf file.tar.gz
            description: Cleans up
    files:
      - source: file.tar.gz
        target: /tmp/remote_file.tar.gz
```

---

__However__, you have properly identified that `onCreate.before` actions are run __after__ import composition has run. During composition the filepaths of all resources are checked, and your example errors because the filepath is created __after__ it is checked.

There are 2 paths forward I will bring up to the team:

1. Disable path checking during composition and wait for the copy operation to fail during create
2. Run `onCreate.before` actions during composition and ignore duplication of that action during create
