### ISSUE TITLE
Helm chart clobbering within components

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#1765]
### Steps to reproduce

Given the following `zarf.yaml` in a directory side by side w/ the Zarf repo:

```yaml
kind: ZarfPackageConfig
metadata:
  name: scratch
  version: 0.0.1

components:
  - name: helm-charts-clobbering
    required: false
    charts:
      - name: podinfo
        localPath: ../zarf/examples/helm-charts/chart
        namespace: chart-1
        version: 6.3.5
      - name: oci-demo
        version: 6.3.5
        namespace: chart-2
        url: oci://ghcr.io/stefanprodan/charts/podinfo
    images:
      - ghcr.io/stefanprodan/podinfo:6.3.5
```

1. `zarf package create . --confirm`
2. `zarf tools archiver decompress zarf-package-scratch-amd64-0.0.1.tar.zst unpacked --unarchive-all`
3. `tree unpacked/components`

### Expected result

2 charts shown

### Actual Result

```
unpacked/components
└── helm-charts-clobbering
    └── charts
        └── oci-demo-6.3.5.tgz
```

Since the 2nd Helm chart is also `podinfo`, it clobbers the first one and destroys the expected `podinfo-6.3.5.tgz`. This results in a broken package as only the final `podinfo` chart will be saved.

### Severity/Priority

IDK, you _really_ shouldn't be using multiple Helm charts with the same _exact_ name and version within a single component (kinda an antipattern tbh), so not really sure where this falls. Opened the issue for tracking.

### Additional Context
Add any other context or screenshots about the technical debt here.
