### ISSUE TITLE
Git Tag and Chart Version assumed to match

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1766]
### Steps to reproduce
Create a zarf.yaml with this component:

```yaml
  - name: dcgm-exporter
    required: true
    charts:
    - name: dcgm-exporter
      version: 3.1.7-3.1.4 # <- this tag doesn't match the chart version
      url: https://github.com/NVIDIA/dcgm-exporter.git
      gitPath: deployment
      namespace: "leapfrogai"
    images:
      - "nvcr.io/nvidia/k8s/dcgm-exporter:3.1.7-3.1.4-ubuntu20.04"
   ```

This particular application has a mismatch between the git tag and the chart version.  This causes an error in either one of two ways since those two are assumed to match:

1. Build error: If using the version matching the chart version, the package doesn't build since Zarf can't find the Git Tag
2. Deploy Error:  If using the git tag, zarf can't deploy the chart since it can't find a chart with the provided version

### Expected result

Be able to deploy an arbitrary chart version from a git repository

### Additional Context
Add any other context or screenshots about the technical debt here.

Ideas/for implementation:

1. Add new property to the `charts` that allows for setting `gitVersion` separately from `version`, but have the default `gitVersion` match the `version` field
2. Add more robust regex on the `url` to allow for passing branch/tag versions in the URL.  Some ambiguity here on backwards compatibility.  If nothing is set, does it default to the default branch, or the `version`?
3. Don't have zarf check to ensure the version matches when deploying a chart from git.
