### ISSUE TITLE
Zarf Skeleton doesn't like components without local files

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1772]
### Environment
Device and OS:
App version:
Kubernetes distro being used:
Other:

### Steps to reproduce
1. Create zarf.yaml with these two components:
```yaml
components
- name: init
  required: true
  files:
    - source: zarf-init-amd64-v0.27.0.tar.zst
      target: zarf-init-amd64-v0.27.0.tar.zst
  actions:
    onDeploy:
      after: 
        - cmd: zarf package deploy zarf-init-amd64-v0.27.0.tar.zst --components git-server --confirm -l warn

# This doesnt work with skeletons...
- name: init2
  required: true
  files:
    - source: https://github.com/defenseunicorns/zarf/releases/download/###ZARF_PKG_TMPL_ZARF_VERSION###/zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst
      target: zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst
  actions:
    onDeploy:
      after: 
        - cmd: zarf package deploy zarf-init-amd64-###ZARF_PKG_TMPL_ZARF_VERSION###.tar.zst --components git-server --confirm -l warn

```

and then publish:

```shell
...
 •  Publishing package to ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
  ✔  Prepared 5 layers                                                                                                                 
  ✔  f1300d0e063c [application/vnd.unknown.config.v1+json]                                                                             
  ✔  48bd8337026e checksums.txt                                                                                                        
  ✔  6e062498132a components/k3d.tar                                                                                                   
  ✔  a256ce800e85 components/metallb.tar                                                                                               
  ✔  7cbacd56c651 zarf.yaml                                                                                                            
  ✔  64e397cf3c44 components/init.tar                                                                                                  
  ✔  236014225522 [application/vnd.oci.image.manifest.v1+json]                                                                         
  ✔  Published ghcr.io/runyontr/k3d-local:v1.26.0-skeleton [application/vnd.oci.image.manifest.v1+json]                                

  •  Example of importing components from this package:

...
```
and note the init2.tar never gets created and pushed.  

Then using that component in a zarf.yaml:

```yaml
  - name: import-init
    required: true
    import:
      name: init2
      url: oci://ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
```


```shell
zarf package create .
...
  •  Pulling Zarf package from ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
  ✔  7cbacd56c651 zarf.yaml                                                                                                                                                                                                                                                                    
  ✔  48bd8337026e checksums.txt                                                                                                                                                                                                                                                                
  ✔  236014225522 [application/vnd.oci.image.manifest.v1+json]                                                                                                                                                                                                                                 
  ✔  Pulling Zarf package data (556.26 MBs)                                                                                                                                                                                                                                                    
  ✔  Pulled ghcr.io/runyontr/k3d-local:v1.26.0-skeleton
     ERROR:  Failed to create package: unable to compose component import-init: unable to get child component:
             unable to unpack composed component tarball: opening source archive: open
             /home/tom/.zarf-cache/oci/ghcr.io/runyontr/k3d-local:v1.26.0-skeleton/components/init2.tar: no such
             file or directory
```


### Expected result

### Actual Result

### Visual Proof (screenshots, videos, text, etc)

### Severity/Priority

### Additional Context
Since there's no local file to put into a tar, I think it's reasonable for nothing to get pushed up, but then the package create shouldn't need to expect it.
