### ISSUE TITLE
Enhance Zarf Skeleton Functionality

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#1808]
### Is your feature request related to a problem? Please describe.
Running on Zarf version 0.27.1, I'm attempting to import published Zarf skeleton components from the this [zarf.yaml](https://github.com/defenseunicorns/uds-package-dubbd/blob/main/aws/zarf.yaml)
Given the following `zarf.yaml`

```yaml
kind: ZarfPackageConfig
metadata:
  name: dubbd-skeleton-example
  version: "0.0.1"
  architecture: amd64  

variables:
- name: STATE_BUCKET_NAME
  description: "Name of the pre-existing Terraform state S3 bucket"
- name: STATE_KEY
  description: "Path to the state file key in the state bucket"
- name: STATE_DYNAMODB_TABLE_NAME
  description: "Name of the DynamoDB table used for Terraform state locking"
- name: REGION
  description: "The AWS region to run the Terraform in"
- name: LOKI_FORCE_DESTROY
  description: "Provide a means to force destroy the Loki storage (S3) bucket even if it contains data"
  default: "false"

components: 
  - name: import-loki-module
    required: true
    import:
      name: loki-module
      url: oci://ghcr.io/defenseunicorns/packages/dubbd-aws:0.2.2-skeleton
  
  - name: import-execute-terraform
    required: true
    import:
      name: execute-terraform
      url: oci://ghcr.io/defenseunicorns/packages/dubbd-aws:0.2.2-skeleton
 
  - name: import-outputs
    required: true
    import:
      name: outputs
      url: oci://ghcr.io/defenseunicorns/packages/dubbd-aws:0.2.2-skeleton
```

With the `zarf-config.yaml`:

```yaml
package:
  create:
    max_package_size: "1000000000"
    set:
      bigbang_version: "2.2.0"
      flux_version: "0.41.2"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
  deploy:
    set:
      domain: bigbang.dev
      public_key_file: bigbang.dev.key
      public_cert_file: bigbang.dev.cert
      name: "gedd-dev" # maybe inject something here for the GH PR?
      state_bucket_name: uds-dev-state-bucket
      state_key: tfstate/dev/uds-dev-state-bucket.tfstate
      state_dynamodb_table_name: uds-dev-state-dynamodb
      region: us-west-2
```

Running `zarf package create` yields the following error message:
![Screenshot 2023-06-11 at 11 02 44 AM](https://github.com/defenseunicorns/zarf/assets/42304551/1bd10154-4400-4445-8e20-c781806cf9e3)

Noting that the [Terraform files](https://github.com/defenseunicorns/uds-package-dubbd/tree/main/aws/loki) referenced in the loki-module component are being copied to my `.zarf-cache`

From @Racer159 : "The issue is the way the skeleton is created / imported - zarf modifies the paths of the file imports to point to a location it controls - it would be difficult to get around this though we might be able to add more file path prefix options like ###ZARF_TEMP###"
