### ISSUE TITLE
Feature Request: Can you vendor in tea cli?

### ISSUE THREAD

**Issue by neoakris** [defenseunicorns/zarf#181]
I Plan to use tea (gitea's cli written in go) to help populate / automate gitea hosted on zarf. Since it's a go app can it be vendored into zarf similar to crane?

The following is a valid command today: 
`zarf tools registry catalog registry.bigbang.dev`

`zarf tools -h`
```
Usage:
  zarf tools [command]

Available Commands:
  archiver           Compress/Decompress tools
  get-admin-password Returns the Zarf admin password read from ~/.git-credentials
  registry           Collection of registry commands provided by Crane
```

Can gitea's tea be vendored in as well, since it's also written in go. (no rush as tea 0.8.0 has the limitation of not being able to create organizations anyways)

https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/near-edge-deployment/-/blob/e619ae5c86077bb3d6fbebde7bd8c8cf5b7959f0/deploy_and_populate_zarf.md#populating-zarfs-git-repo
^-- has more context but here's the relevant part 
(you have to pre-create empty repos in order to git push repo1 upstream repos into the empty gitea git repos)

```
# Step 3 use tea to precreate 25 empty repos in gitea
# install tea (gitea's cli)
curl -L https://dl.gitea.io/tea/0.8.0/tea-0.8.0-linux-amd64 > tea
sudo chmod +x tea
sudo mv tea /usr/bin/tea

# login to gitea from the cli
tea login add --name admin --url https://git.bigbang.dev --user=$GIT_USER --password=$GIT_PASS
tea login list
tea login default admin set 
tea login list

# create 25 repos
ls -1 /root/repos | xargs --replace={item} tea repo create --name={item} --owner=platform-one 
# The above command is basically running this command 25 times, with 25 different values for $REPO_NAME
# tea repo create --name=$REPO_NAME --owner=platform-one
```

**Comment by jeff-mccoy** [comment]
Since we make gitea a core part of the gitops service / utility cluster this does seem reasonable, though I'm waffling a bit on vendoring into the CLI vs just bringing their binary into the gitops-service component instead. I vendored those CLI endpoints because we already were using the code in the codebase, so sharing with the user didn't increase the binary size really.  I'd be curious to see what binary size would be vendored in tho the CLI vs just bringing the `tea` binary as a part of the gitops-service component.  E.g.:

```yaml
  - name: gitops-service
    description: "Add Registry and Gitea for serving gitops-based clusters in an airgap"
    files:
      - source: https://gitea.com/attachments/bba60977-7066-4376-b232-941855b6015b
        shasum: 8bc99e0532548365f3d86a5ec319772121a844d54a01cb51cddb030d05f27a0c
        target: /usr/local/bin/tea
        executable: true
```
