### ISSUE TITLE
Slim init package for external registry and git repository

### ISSUE THREAD

**Issue by laurentiusoica** [defenseunicorns/zarf#1839]
With external registry and repository, I don't need the zarf registry or the git components. But if I build a custom init package and I don't include the registry replated components, the cluster is not initialized; the state secret object is not there under zarf namespace.

**Comment by Racer159** [comment]
Thanks for the issue!

Definitely going to keep this one open as we look to modularize our init process more and more.

Currently Zarf looks for an init component named `zarf-seed-registry` as a marker that it is passed the `k3s` component and has a K8s cluster that it can talk to. To get around this currently you can create an empty required component that is called `zarf-seed-registry` as below:

```
kind: ZarfInitConfig
metadata:
  name: init
  description: Used to establish a new Zarf cluster

components:
  # Creates the temporary seed-registry
  - name: zarf-seed-registry
    required: true

  # Creates the pod+git mutating webhook
  - name: zarf-agent
    required: true
    import:
      path: packages/zarf-agent
```
