### ISSUE TITLE
Multi-layered imports do not adjust filepaths correctly

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/zarf#1845]
### Environment
Device and OS: MBP, macOS
App version: 0.27.1
Kubernetes distro being used: N/A

### Steps to reproduce
1. Clone https://github.com/mjnagel/layers-of-cake
2. `zarf package create`
3. Observe during confirmation that only the "bottom" import has its paths adjusted correctly.

### Expected result

All layers of imports should have filepaths adjusted to be relative to the import path.

### Actual Result

Only the last imported component will be adjusted correctly. Note that this was reproduced with both 3 & 4 layers, and I assume this could be extended indefinitely.

### Visual Proof (screenshots, videos, text, etc)

```
kind: ZarfPackageConfig
metadata:
  name: parent
components:
- name: file
  required: true
  files:
  - source: leaf/lfile.txt
    target: lfile.txt
  - source: cfile.txt
    target: cfile.txt
  - source: sfile.txt
    target: sfile.txt
  - source: file.txt
    target: file.txt
```

### Severity/Priority

No clear workaround outside of symlinks, etc to make paths work.

### Additional Context

This was originally seen with the bigbang extension values files, but it seems to affect all places where imported components need to adjust filepaths.
