### ISSUE TITLE
Cannot stop process when in the middle of a `wait`

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#1864]
When a Zarf package has a `wait` target described, the CLI does not receive `ctrl + c` commands to stop the process. The default timeout for a `wait` is five minutes meaning a user who wants to stop the deployment is unable to cancel the process during those five minutes.

Example `wait` specification:
```yaml
components:
  - name: wait-component
     actions:
      onDeploy:
        after:
          # This will use a wait action to wait for the podinfo pod to be ready
          - description: Podinfo pods to be ready via wait action
            wait:
              cluster:
                kind: pod
                name: app=podinfo
                namespace: podinfo
                condition: ready
```
