### ISSUE TITLE
JSONPath wait-for condition

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/zarf#1872]
### Is your feature request related to a problem? Please describe.
As a Zarf practitioner, I want to have fine grained control over my wait command in times of automation, complex package deployments, tutorials, etc. I need to get extremely specific in terms of the things that I wait for. The given wait values do not work in certain cases, like for instance for StatefulSets. For these specific use-cases, I need to utilize a JSON path to point to a specific status in the object.

### Describe the solution you'd like

- **Given** that I issue a `zarf tools wait-for`
- **When** the wait value has this pattern `'{.x.y}'=z`
- **Then** I want zarf to interpret that is a JSONPath wait 

### Describe alternatives you've considered
Using `kubectl`

```bash
# --for=jsonpath='{}'=value
# Wait for the pod "busybox1" to contain the status phase to be "Running".
kubectl wait --for=jsonpath=“{.status.availableReplicas}”=2 sts/test-sts
kubectl wait --for=jsonpath='{.status.phase}'=Running po/busybox1
kubectl wait --for=jsonpath='{.status.containerStatuses[0].ready}'=true po/busybox1
kubectl wait --for=jsonpath='{.spec.containers[0].ports[0].containerPort}'=80 po/busybox1
kubectl wait --for=jsonpath='{.spec.nodeName}'=knode0 po/busybox1
```

### Additional context

Pain Points:

```yaml
kubectl create -f -<<EOF
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: test-sts
  name: test-sts
spec:
  replicas: 23
  selector:
    matchLabels:
      app: test-sts
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-sts
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
EOF
zarf tools wait-for sts test-sts exists

# Need finer grain control -- I want to know when all the replicas are ready
# ./build/zarf-mac-apple tools wait-for sts test-sts '{.status.availableReplicas}'=23
```

In the examples/scraping-zarf-agent I am deploying an instance of Prometheus which makes the operator deploy a `sts`. I don't have a wait for the replicas to be ready and I don't want the user to continue until they are

```yaml
kind: ZarfPackageConfig
metadata:
  name: scrape-zarf-agent
  yolo: false
  description: Scrape Zarf Agent with Prometheus Operator.

components:
  - name: prometheus-deps
    required: true
    manifests:
      - name: prometheus-deps
        namespace: monitoring
        files:
          - manifests/prometheus-deps/bundle.yaml
    images:
      - quay.io/prometheus-operator/prometheus-operator:v0.66.0
    actions:
      onDeploy:
        after:
          - wait:
              cluster:
                kind: deployment
                name: prometheus-operator
                namespace: monitoring
                condition: available
  - name: prometheus-operator
    required: true
    manifests:
      - name: prometheus-operator
        namespace: monitoring
        files:
        - manifests/prometheus-operator/prometheus.yaml
        - manifests/prometheus-operator/servicemonitor-agent.yaml
        - manifests/prometheus-operator/clusterrole.yaml
        - manifests/prometheus-operator/clusterrolebinding.yaml
    images:
      - quay.io/prometheus/prometheus:v2.45.0
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.66.0
    # This is not gonna work 
    # actions:
    #   onDeploy:
    #     after:
    #       - wait:
    #           cluster:
    #             kind: statefulset
    #             name: forgot-the-name
    #             namespace: monitoring
    #             condition: available
```
