### ISSUE TITLE
Zarf files archive path support

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1928]
### Is your feature request related to a problem? Please describe.
Often binaries or other files that need to be included in a Zarf package are contained inside of archives (zip / tar) and need to be extracted to be used.  This currently requires an additional script or action which clutters the `zarf.yaml`.

### Describe the solution you'd like

- **Given** I have a `zarf.yaml` that specifies a file archive
- **And** I specify an `archivePath`

```yaml
    files:
      - source: https://github.com/weaveworks/eksctl/releases/download/v0.146.0/eksctl_Darwin_amd64.tar.gz
        target: ~/.zarf/bin/eksctl
        shasum: 2e3faa90e3adf639aed4dbefd7691f73f4b2a21d64d907e6bdbc086cd79bf275
        archivePath: eksctl
```

- **When** I create the package
- **Then** the archive is extracted and only the internal file or directory is included in the package
- **And** the SHASUM I provide would be that of the source archive

### Describe alternatives you've considered
We could add an addition unarchive action type (similar to wait) but this action is not normally life cycle specific and likely would not make sense being done in this way.

### Additional context
Common binaries like flux are distributed this way and in use in zarf packages today: https://github.com/defenseunicorns/uds-package-dubbd/blob/6c00497870b7bed3ce1b03554705b20dda746c41/defense-unicorns-distro/zarf.yaml#L138

**Comment by cmwylie19** [comment]
This works for files, and folders including non-urls

```yaml
      - source: hi.tar.gz
        target:  something/hi.txt
        shasum: aadc1955c030f723e9d89ed9d486b4eef5b0d1c6945be0dd6b7b340d42928ec9
        archivePath: hi.txt
 ```
