### ISSUE TITLE
YAML spec 1.2 merge alias makes zarf config invalid

### ISSUE THREAD

**Issue by Marvin0098** [defenseunicorns/zarf#1946]
### Environment
Device and OS: Mac
App version: 0.28.3
Kubernetes distro being used: 
Other:

### Steps to reproduce
1. My current zarf config looks like this:
```
kind: ZarfPackageConfig
metadata:
  name: zarf-package
  version: 0.0.1
variables:
  - &var
    name: URL
    description: "N/A"
    prompt: false
  - <<: *var
    name: GITEA
```
When I create a Zarf Package with this config it works fine. But with YAML spec 1.2, they added `!!merge` to these nodes. And this causes an issue when I create a package with this configuration:

```
kind: ZarfPackageConfig
metadata:
  name: zarf-package
  version: 0.0.1
variables:
  - &var
    name: URL
    description: "N/A"
    prompt: false
  - !!merge <<: *var
    name: GITEA
```

I use yq to change values in the yaml file, and it automatically adds the `!!merge` tags. Since in YAML 1.2 spec the `<<:` alias is handled as an custom tag it needs to be replaced.
More info from yq about this https://mikefarah.gitbook.io/yq/operators/anchor-and-alias-operators#explode-with-no-aliases-or-anchors.

Error message when I run the second config with `zarf package create`

```
Failed to create package: unable to read the zarf.yaml file: [11:5] tag was used where mapping is
             expected 8 | name: GITEA_URL 9 | description: "N/A" 10 | prompt: false > 11 | - !!merge <<: *var ^

```

Is the YAML Spec 1.2 supported by zarf?

### Additional Context
Add any other context or screenshots about the technical debt here.
