### ISSUE TITLE
zarf prepare find-images does not break if any of the valueFiles of the helm charts are invalid

### ISSUE THREAD

**Issue by alinalex1392** [defenseunicorns/zarf#1999]
### Environment
Device and OS:  Linux coder-alinbaicu-alin-terraform-embed 5.15.0-1028-aws #32~20.04.1-Ubuntu SMP Mon Jan 9 18:02:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
App version: github.com/defenseunicorns/zarf v0.28.2
Kubernetes distro being used: N/A
Other:N/A

### Steps to reproduce
1. Create a zarf.yaml file prepared for listing the images for a helm chart:

```yaml
kind: ZarfPackageConfig
metadata:
  name: list_images
  description: ""
  version: 0.1.0-206.g72ec536 
components:
- name: charts
  charts:
  - name: podinfo
    releasename: helloworld
    url: oci://ghcr.io/stefanprodan/charts/podinfo
    version: 6.3.3
    namespace: application
    valuesFiles:
    - /home/coder/service-secretmanagement-helm/zarf-test/helloworld-env-values.yaml
```

2. The value file should be an invalid yaml:

```yaml
replicaCount: - asd

image:
  repository: stefanprodan/podinfo
  tag: 6.4.1
  pullPolicy: IfNotPresent
```

3. Zarf behavior is just to show a warning and not break on the execution:

```shell
zarf prepare find-images  --kube-version 1.23.0-0
```

```text
 WARNING  Problem rendering the helm template for oci://ghcr.io/stefanprodan/charts/podinfo: unable
          to load chart data: unable to parse chart values: failed to parse
          /tmp/zarf-1472537511/components/charts/values/podinfo-6.3.3-0: error converting YAML to
          JSON: yaml: block sequence entries are not allowed in this context
```

### Expected result

The expected result is to break and the command should  return exit code 1
The default behavior of helm template is to break in case the valueFiles are invalid yamls.

### Actual Result

The command only print the warning and it return with success exit code 0

### Additional Context
Add any other context or screenshots about the technical debt here.
