### ISSUE TITLE
Package Removal Fails Under Specific Conditions

### ISSUE THREAD

**Issue by KaylCoulston** [defenseunicorns/zarf#2029]
### Environment
Device and OS: RHEL 8.4
App version: v0.29.2
Kubernetes distro being used: k3s
Other: Used zarf  v0.29.2 default init package

### Steps to reproduce
1. `zarf init`
2. create zarf.yaml (combination of subsets of both the [component-actions](https://docs.zarf.dev/examples/component-actions/) and [helm-charts](https://docs.zarf.dev/examples/helm-charts/) examples)
```
kind: ZarfPackageConfig
metadata:
  name: helm-charts-and-actions
  description: Example showing bug when deploying helm charts and components with only actions
  version: 0.0.1

components:
  - name: demo-helm-oci-chart
    required: false
    charts:
      - name: podinfo
        version: 6.4.0
        namespace: podinfo-from-oci
        url: oci://ghcr.io/stefanprodan/charts/podinfo
    images:
      - ghcr.io/stefanprodan/podinfo:6.4.0

  - name: on-deploy-and-remove
    actions:
      # runs during "zarf package deploy"
      onDeploy:
        # runs before the component is deployed
        before:
          - cmd: touch test-deploy-before.txt
        # runs after the component is deployed
        after:
          - cmd: touch test-deploy-after.txt
      # runs during "zarf package remove"
      onRemove:
        # runs before anything else from the component is removed
        before:
          - cmd: rm test-deploy-before.txt
        # runs after everything else from the component is removed
        after:
          - cmd: rm test-deploy-after.txt
```
3. `zarf package deploy zarf-package-helm-charts-and-actions-amd64-0.0.1.tar.zst`
4. `zarf package remove zarf-package-helm-charts-and-actions-amd64-0.0.1.tar.zst --confirm`
5. Confirm both of the components are removed using `zarf package list`

### Expected result
After this sequence of events you would expect both the zarf components in the `helm-charts-and-actions` package to be removed.

### Actual Result
Currently only the removal for the `on-deploy-and-remove` component is executed. Also, even though the removal is executed it still shows up when running `zarf package list`.

I have not found a way to clean up components and packages that are listed in the package list after this occurs. The only way I have been able to recover is to execute a `zarf destroy --confirm`, setup the zarf agent (when running my own cluster) and then deploy my packages components separately.

### Visual Proof (screenshots, videos, text, etc)
N/A, zarf package is provided using Defense Unicorns examples. 

### Severity/Priority
N/A

### Additional Context
N/A
