### ISSUE TITLE
Zarf validate schema

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2034]
I would like zarf to check my yaml file and validate that I am following the schema. 
For example if in my zarf.yaml I have
```
- name: actions-runner-controller
  required: true
  chart:      
    - name: runner-scale-set-controller
      releaseName: runner-scale-set-controller
      url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
      version: 0.4.0
      namespace: arc-systems
      valuesFiles:
        - "runner-scale-set-controller/values.yaml"
```
zarf should recognize that chart is not an appropriate field (it should be charts with an s) and fail with a message instructing the user in some way to fix it. 

### Describe the solution you'd like

- **Given** I have a zarf.yaml that does not follow the zarf schema
- **When** I execute zarf package create 
- **Then** zarf gives me an error 

### Describe alternatives you've considered
Further encourage use of the zarf schema in the docs / through the cli - we could maybe do that too but I figure the approach of just failing bad files would be better

### Questions I have 
- Would we want a method to turn off validation like validate=false in kubectl? 
- How worried are we about breaking changes? This could fail some charts that we were working but technically have something unnoticed wrong in the schema like a default variable that is getting overwritten anyway.
