### ISSUE TITLE
Zarf 0.30.0 wait-for not working in some scenarios

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/zarf#2054]
### Environment
Device and OS: Macos, MBP
App version: 0.30.0
Kubernetes distro being used: k3d

### Steps to reproduce

Option 1:

- Build/deploy the below package with zarf 0.29.2 and zarf 0.30.0, against a default k3d cluster:

```yaml
kind: ZarfPackageConfig
metadata:
  name: test
components:
  - name: bar
    actions:
      onDeploy:
        after:
          - wait:
              cluster:
                kind: APIService
                name: v1beta1.metrics.k8s.io
```

Option 2:

- Run the following commands against a default k3d cluster:

```console
❯ zarf-30 tools wait-for apiservice v1beta1.metrics.k8s.io -n default
  ✔  Waiting for apiservice/v1beta1.metrics.k8s.io in namespace default to exist.                                                                                                                               
❯ zarf-30 tools wait-for apiservice v1beta1.metrics.k8s.io -n ""
  ⠦  Waiting for apiservice/v1beta1.metrics.k8s.io to exist. (3s)^C                                                                                                                                             
❯ zarf-30 tools wait-for apiservice v1beta1.metrics.k8s.io
  ⠦  Waiting for apiservice/v1beta1.metrics.k8s.io to exist. (3s)^C                                                                                                                                             
```

(the first one passes, the others fail)

### Expected result

The wait-for behavior should be the same across these versions.

### Actual Result

Wait-for seems to fail in some scenarios, possibly due to namespace handling behavior with the kubectl library update?

### Visual Proof (screenshots, videos, text, etc)

Included logs above for CLI behavior.

### Severity/Priority

Breaks the BB extension due to the metrics server wait included there.
