### ISSUE TITLE
zarf prepare find-images is not consistent between OCI and Helm chart registries

### ISSUE THREAD

**Issue by alinalex1392** [defenseunicorns/zarf#2062]
### Environment
Device and OS:
- NAME="Ubuntu"
- VERSION="20.04.5 LTS (Focal Fossa)"
App version: v0.30.0
Kubernetes distro being used: None
Other: CLI usage

### Steps to reproduce
1. Execute 

```sh
zarf prepare find-images -l debug --kube-version=1.23.0-0
```

```yaml
kind: ZarfPackageConfig
metadata:
  name: helm-charts
  description: Example showcasing mutiple ways to deploy helm charts
  version: 0.0.1
components:
  - name: demo-helm-oci-chart
    charts:
      - name: asdasd
        version: 6.4.0
        namespace: podinfo-from-oci
        url: oci://ghcr.io/stefanprodan/charts/podinfo
  - name: demo-helm-alt-release-name
    charts:
      - name: podinfo
        version: 6.4.0
        namespace: helm-alt-release-name
        url: https://stefanprodan.github.io/podinfo/podinfo
        releaseName: cool-name
```

The list of images is gathered correctly, even though the name from the demo-helm-oci-chart component is being wrong.

Later Edit:

If I change the component  demo-helm-oci-chart name to asdasd/podinfo then the command fail and the name is taken into consideration:

```yaml
kind: ZarfPackageConfig
metadata:
  name: helm-charts
  description: Example showcasing mutiple ways to deploy helm charts
  version: 0.0.1
components:
  - name: demo-helm-oci-chart
    charts:
      - name: asdasd/podinfo
        version: 6.4.0
        namespace: podinfo-from-oci
        url: oci://ghcr.io/stefanprodan/charts/podinfo
  - name: demo-helm-alt-release-name
    charts:
      - name: podinfo
        version: 6.4.0
        namespace: helm-alt-release-name
        url: https://stefanprodan.github.io/podinfo/podinfo
        releaseName: cool-name
```
Logs:

```text
  DEBUG   2023-10-10T12:39:42Z  -  Reading YAML at zarf.yaml
  DEBUG   2023-10-10T12:39:43Z  -  rename /tmp/zarf-1580237310/components/demo-helm-oci-chart/charts/podinfo-6.4.0.tgz /tmp/zarf-1580237310/components/demo-helm-oci-chart/charts/asdasd/podinfo-6.4.0.tgz: no such file or directory
     ERROR:  Unable to save the chart tarball
```

### Expected result

Both components should use the name key or have consistency between their configs.

### Actual Result

On the demo-helm-oci-chart component the name is taken into consideration but on the demo-helm-alt-release-name component based on OCI registry is not.
