### ISSUE TITLE
localPath for charts won't accept tarball

### ISSUE THREAD

**Issue by j2udev** [defenseunicorns/zarf#2063]
### Environment
Device and OS: M1 Macbook Pro
App version: v0.28.4
Kubernetes distro being used: n/a
Other:

### Steps to reproduce
Just create a zarf package that leverages the charts component and point the localPath attribute at the chart tarball

### Expected result
I would expect the above to work as it does for the Helm CLI

### Actual Result
The zarf package create command fails validation stating that it was unable to package the chart: Chart.yaml file is missing

(I appreciate that zarf is trying to validate my chart, but I can validate my own chart if it means that I can avoid needing to decompress my chart)

### Visual Proof (screenshots, videos, text, etc)
In this component, I have the hack I'm using to get around this commented out, but it would be nice if I didn't need to:

```yaml
components:
  - name: local
    required: false
    charts:
      - name: cert-manager
        namespace: test
        localPath: charts/cert-manager-v1.12.2.tgz
        # localPath: charts/cert-manager
        version: v1.12.2
        valuesFiles:
          - bundles/values.yaml
    # actions:
    #   onCreate:
    #     before:
    #       - dir: charts
    #         cmd: tar xf cert-manager-v1.12.2.tgz
    #     after:
    #       - dir: charts
    #         cmd: rm -r cert-manager ; exit 0
```

### Additional Context
If I have overlooked a way to get this to work, my apologies, but I searched around and nothing jumped out right away.
