### ISSUE TITLE
`prepare find-images` should print available chart names upon name mismatch

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#2070]
`prepare find-images` has an unhelpful error message when it fails to find a chart.

### Describe the solution you'd like

Given:

```yaml
kind: ZarfPackageConfig
metadata:
  name: istio
  version: 0.0.1

components:
  - name: istio-controlplane
    required: true
    charts:
      - name: istio
        namespace: istio-system
        url: https://istio-release.storage.googleapis.com/charts
        version: 1.19.3
```

will result in:

```
  DEBUG   2023-10-13T13:43:59-05:00  -  chart "istio" version "1.19.3" not found in https://istio-release.storage.googleapis.com/charts repository     
     ERROR:  Unable to pull the helm chart
```

I would like something like: `chart "istio" version "1.19.3" does not exist, but X, Y, Z do`

and show the output of:

```bash
curl -sL https://istio-release.storage.googleapis.com/charts/index.yaml | yq '.entries | keys'

- base
- cni
- gateway
- istiod
- ztunnel
```
