### ISSUE TITLE
Better handling of package templates with numeric names

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#2074]
### Describing What Works
If you have the following project structure:
```yaml
# example zarf-config.yaml
package:
  create: 
    set:
      k3d_version: 5.5.2
```
```yaml
# example zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: this-correctly-validates
 
components:
- name: download-assets
  required: true
  files:
    - source: https://github.com/k3d-io/k3d/releases/download/v###ZARF_PKG_K3D_VERSION###/k3d-linux-amd64
      target: k3d
      executable: true
```

Then running the `zarf package create . --confirm` command executes without any issues.

### Describing What Doesn't Work
If you were to remove the `zarf-config.yaml` file and re-run the create command without any changes, I would expect to see a warning stating
```
     ERROR:  Failed to create package: unable to fill values in template: template 'K3D_VERSION' must be '--set'
             when using the '--confirm' flag
```

Currently this doesn't happen and you end up receiving an error because zarf it attempting to download from a nonexistant url 
```
     ERROR:  Failed to create package: unable to add component: failed to download
             https://github.com/k3d-io/k3d/releases/download/v###ZARF_PKG_TMPL_K3D_VERSION###/k3d-linux-amd64:
             bad HTTP status: 404 Not Found
```
I would not expect Zarf to do this because it should have noticed that a `ZARF_PKG_TMPL...` variable value was not provided.

## Describe alternatives you've considered

Removing the digit `3` from the template results in the warning I expected. When I run the `zarf package create . --confirm` command I get the warning message that I'm not supplying a necessary value for a template (note the template name is now `KD_VERSION` instead of `K3D_VERSION`:

```
     ERROR:  Failed to create package: unable to fill values in template: template 'KD_VERSION' must be '--set'
             when using the '--confirm' flag
```

## Desired Outcome
As a package creator, I expect to be warned if I'm forgetting to supply a mandatory template value. I would expect zarf to either
a) Warn me that I my zarf.yaml has an invalid configuration (in this case an invalid character (0-9) in my template name)
b) Tell me that I'm forgetting to provide the value for a mandatory template.
