### ISSUE TITLE
Broken image references to `docker.io`

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#2086]
Image references to images at root of `docker.io` are  mutated during create, leading to a mismatch between the `zarf.yaml` and the `index.json` within the package. This is handled during the reading of a Zarf package as a tarball, but will fail when fetched as OCI.

---

given the following `zarf.yaml`:

```yaml
kind: ZarfPackageConfig
metadata:
  name: scratch

components:
  - name: some-images
    required: true
    images:
      - docker.io/nginx:latest
      - redis:latest
      - docker.io/library/alpine:latest
```

and:

```bash
zarf package create . --confirm
zarf tools archiver decompress zarf-package-scratch-amd64.tar.zst package-scratch
cat package-scratch/images/index.json | jq ".manifests | .[] .annotations"
```

yields:

```json
{
  "org.opencontainers.image.base.name": "docker.io/library/nginx:latest"
}
{
  "org.opencontainers.image.base.name": "docker.io/library/redis:latest"
}
{
  "org.opencontainers.image.base.name": "docker.io/library/alpine:latest"
}
```

but:

```bash
cat package-scratch/zarf.yaml | yq '.components .[] .images'
```

yields:

```yaml
- docker.io/nginx:latest
- redis:latest
- docker.io/library/alpine:latest
```
