### ISSUE TITLE
Add an `only.flavor` key to Zarf components

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2101]
### Is your feature request related to a problem? Please describe.
**As** Ezra **I want** the ability to specify "flavors" of Zarf packages and select between them on `zarf package create` **so that** I can swap chunks of things like `images` and `valuesFiles` without the need to have an entirely separate copy of a Zarf package definition.

### Describe the solution you'd like

- **Given** I have a Zarf package definition
- **And** that definition has components that specify `only.flavor`
- **When** I run `zarf package create --flavor my-flavor`
- **Then** Zarf will include all components that match that flavor or have an empty flavor string
- **And When** I run `zarf package create` without a `flavor`
- **Then** Zarf will include only components that have an empty flavor string

### Describe alternatives you've considered
We could have higher order keys like `imageSets` or have other extensions but this adds complexity without taking advantage of a lot of the base Zarf primitive manipulation that can be done through composability.

### Additional context
This initial ask came from a desire to swap images to have a hardened and an upstream version of the same underlying package to help with package development and testing.

**Comment by jeff-mccoy** [comment]
Here's an example we worked through for Istio 1.19 where there would be an `ironbank` and `upstream` flavor:

```yaml
kind: ZarfPackageConfig
metadata:
  name: uds-capabilities-istio
  description: "UDS Istio Capability"
  url: https://istio.io/latest/
  version: 1.19.0

components:
  - name: istio-controlplane
    import:
      path: common
    only:
      flavor: upstream
    images:
      - "docker.io/istio/pilot:1.19.0"
      - "docker.io/istio/proxyv2:1.19.0"

  - name: istio-controlplane
    import:
      path: common
    charts:
      - name: istiod
        valuesFiles:
          - "values/ironbank.yaml"
    only:
      flavor: ironbank
    images:
      - "registry1.dso.mil/ironbank/opensource/istio/pilot:1.19.0"
      - "registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.19.0"
  ```
