### ISSUE TITLE
Expand Zarf variables in onDeploy action wait blocks / load variables during component removes

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#2130]
### Is your feature request related to a problem? Please describe.

Zarf does not expand Zarf variables in action wait blocks. Zarf package developers cannot verify the readiness of resources deployed into deploy-time named namespaces.

### Describe the solution you'd like

- **Given** a Zarf package that deploys resources into a deploy-time named/created namespace
- **When** Zarf onDeploy action wait block includes the Zarf variable for the namespace
- **Then** Zarf expands the namespace's value and the wait block successfully verifies resource readiness

### Describe alternatives you've considered
(optional) A clear and concise description of any alternative solutions or features you've considered.

### Additional context

This is a simple Zarf package YAML that exemplifies inconsistent Zarf variable expansion within onDeploy action blocks. The first `cmd` is successful. The nearly identical `wait` block will fail because Zarf does not expand Zarf variables in onDemand action wait blocks.

Steps to reproduce
1. `k3d cluster create`
2. `zarf package create --confirm`
3. `zarf package deploy --confirm zarf-package-action-test-*.tar.zst`

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: action-test

variables:
  - name: TEST_NAMESPACE
    default: kube-system

components:
  - name: test
    required: true
    actions:
      onDeploy:
        after:
          - cmd: ./zarf tools wait-for pod k8s-app=kube-dns Ready -n ${ZARF_VAR_TEST_NAMESPACE} --timeout 10s
          - maxTotalSeconds: 10
            wait:
              cluster:
                kind: pod
                name: k8s-app=kube-dns
                namespace: ###ZARF_VAR_TEST_NAMESPACE###
                condition: Ready

```

The issue was discovered with a more involved Zarf package that has the following characteristics
* Zarf variable for the namespace a PostgreSQL database should be created in `ZARF_VAR_DATABASE_NAMESPACE`
* Helm chart that wraps the Zolando Postgres CRD
    * Helm chart creates a namespace with the Zarf variable `ZARF_VAR_DATABASE_NAMESPACE`
    * Helm chart creates the Zolando Postgres CRD with instructions to instantiate the database in `ZARF_VAR_DATABASE_NAMESPACE`
* Zarf onDeploy.after.wait block waits for the database's master pod to be healthy

**Comment by mikevanhemert** [comment]
Zarf also does not load variables when executing component `actions.onRemove` blocks

Recreate the issue with these steps and the zarf.yaml defined below
1. `zarf package create --confirm`
2. `zarf package deploy zarf-p*.zst --confirm --set MESSAGE=hello-world`
    * *note: message echoed is `hello-world`*
3. `zarf package remove zarf-p*.zst --confirm --set MESSAGE=goodbye-world`
    * *note: zarf provides an error message `Error: unknown flag: --set`*
4. `zarf package remove zarf-p*.zst --confirm`
    * *note: no message echoed because variable is never expanded*

```yaml
kind: ZarfPackageConfig
metadata:
  name: test
  version: 0.1.0

variables:
  - name: MESSAGE
    default: a-hoy-hoy

components:
  - name: test
    required: true
    actions:
      onDeploy:
        after:
          - cmd: echo ${ZARF_VAR_MESSAGE}
      onRemove:
        after:
          - cmd: echo ${ZARF_VAR_MESSAGE}
```

**Comment by jeff-mccoy** [comment]
this does seem like something we should address

**Comment by Racer159** [comment]
On the wait side does `${ZARF_VAR_TEST_NAMESPACE}` work for you in the namespace field?

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: action-test

variables:
  - name: TEST_NAMESPACE
    default: kube-system

components:
  - name: test
    required: true
    actions:
      onDeploy:
        after:
          - cmd: ./zarf tools wait-for pod k8s-app=kube-dns Ready -n ${ZARF_VAR_TEST_NAMESPACE} --timeout 10s
          - maxTotalSeconds: 10
            wait:
              cluster:
                kind: pod
                name: k8s-app=kube-dns
                namespace: ${ZARF_VAR_TEST_NAMESPACE}
                condition: Ready
```

The remove variables are also mentioned in this issue: https://github.com/defenseunicorns/zarf/issues/1801

If the above works should I close this as a dupe of #1801?

Also @jeff-mccoy I assume you were talking about #1801 not the wait stuff? (if so I can reprioritize it higher)
