### ISSUE TITLE
Add a variable shorthand for helm values

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2133]
### Is your feature request related to a problem? Please describe.
As Ezra I want a way to tie Zarf variables to Helm values so that I can more efficiently template values in the packages I build.

### Describe the solution you'd like

- **Given** I have a Helm Chart
- **And** I have a variable I would like to template into its values
- **When** I specify a new key on a chart under `charts` including the Zarf variable and the Helm value
- **Then** that Zarf variable is set as that Helm value on deployments and templates of that chart.

### Describe alternatives you've considered
Folks could use the existing logic and add templates but this simplifies things and allows people to more directly take advantage of Helm templating and featuresets without having to do a lot of manual wiring.

### Additional context
This is being implemented in library form first through #2131

**Comment by Racer159** [comment]
An example of how this might look:

```
# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/main/zarf.schema.json
kind: ZarfPackageConfig
metadata:
  name: gitlab-common
  description: "UDS GitLab Common Package"

components:
  - name: gitlab
    required: true
    charts:
      - name: uds-gitlab-config
        namespace: gitlab
        version: 0.1.0
        localPath: ../chart
      - name: gitlab
        namespace: gitlab
        url: https://repo1.dso.mil/big-bang/product/packages/gitlab.git
        gitPath: chart
        version: "7.9.1-bb.0"
        variables:
          - name: MIGRATIONS_RESOURCES
            description: "Gitlab Migrations Resources"
            path: "gitlab.migrations.resources"
          - name: WEBSERVICE_REPLICAS
            description: "Gitlab Webservice Min Replicas"
            path: "gitlab.webservice.minReplicas"
          - name: WEBSERVICE_RESOURCES
            description: "Gitlab Webservice Resources"
            path: "gitlab.webservice.resources"
          - name: WORKHORSE_RESOURCES
            description: "Gitlab Workhorse Resources"
            path: "gitlab.workhorse.resources"
          - name: SIDEKIQ_REPLICAS
            description: "Gitlab Sidekiq Min Replicas"
            path: "gitlab.sidekiq.minReplicas"
          - name: SIDEKIQ_RESOURCES
            description: "Gitlab Sidekiq Resources"
            path: "gitlab.sidekiq.resources"
          - name: REGISTRY_REPLICAS
            description: "Gitlab Registry Min Replicas"
            path: "registry.hpa.minReplicas"
          - name: SHELL_REPLICAS
            description: "Gitlab Shell Min Replicas"
            path: "gitlab.gitlab-shell.minReplicas"
        valuesFiles:
          - ../values/common-values.yaml
```
