### ISSUE TITLE
Zarf 0.31.1: "localOS: ..." Tag in zarf.yaml does not work anymore (on Windows and Linux)

### ISSUE THREAD

**Issue by Ghost-Of-Tsushima** [defenseunicorns/zarf#2158]
### Environment
Device and OS: Linux (and Windows Server 2019)
App version: Zarf v0.31.1
Kubernetes distro being used: k3s with zarf included (running only on Linux)
Other:

### Steps to reproduce
1. Build Zarf Package with Zarf v.0.31.1 on Linux
2. Deploy the same Zarf Package on a Linux system with atleast following zarf.yaml (should be in build too):

```yaml
  - name: basic name
    only:
      localOS: windows
    actions:
      onDeploy:
        after:
          - cmd: "<Placeholder for Powershell-only Command>"
```

3. Build Zarf Package with Zarf v.0.31.1 on Linux
4. Deploy the same Zarf Package on a Windows system with atleast following zarf.yaml (should be in build too):

```yaml
  - name: basic name
    only:
      localOS: linux
    actions:
      onDeploy:
        after:
          - cmd: "<Placeholder for bash/linux-only Command>"
```

### Expected result

- When the first yaml-block (localOS: windows) is run on a Linux System, it should not be interpreted at all by bourneshell and just skipped. When its run on a Windows System, it should be interpreted and run correctly.

- When the seconf yaml-block (localOS: Linux) is run on a Windows System, it should not be interpreted at all by Powershell and just skipped. When its run on a Linux System, it should be interpreted and run correctly.

### Actual Result

- When `zarf deploy <packagename>` is executed on a linux system, there is an error: `sh: 1: Syntax error: <powershell-command, that cant get interpreted by bourneshell>`

- When `zarf deploy <packagename>` is executed on a windows system, there is an error: `Powershell error: <Bash-command that cant get interpreted by powershell>`

### Visual Proof (screenshots, videos, text, etc)
zarf.yaml:
![errorforzarfissue](https://github.com/defenseunicorns/zarf/assets/151738591/5ac31cc2-3ddc-4532-9eb4-217110ab4969)
Powershell-Error:
![errorpowershell](https://github.com/defenseunicorns/zarf/assets/151738591/9090302e-c341-428c-be55-5baa2f166f3a)
Linux-Error:
![yamlerrorlinux](https://github.com/defenseunicorns/zarf/assets/151738591/8b309b23-180e-48a7-add6-35d95439812b)

### Severity/Priority

- Medium, because the functionality above is not working anymore

### Additional Context
I upgraded from Zarf Version v0.29.2 to v0.31.1. In Version v0.29.2 it worked perfectly fine. I didn't alter the code in any shape or form.

**Comment by Racer159** [comment]
@Ghost-Of-Tsushima are you seeing this on v0.31.3 as well?  Testing with this simple example on v0.31.3 and v0.31.1 and I didn't see the same behavior:

```yaml
kind: ZarfPackageConfig
metadata:
  name: test

components:
  - name: basic-name
    required: true
    only:
      localOS: windows
    actions:
      onDeploy:
        after:
          - cmd: echo Windows!
  - name: basic-name2
    required: true
    only:
      localOS: linux
    actions:
      onDeploy:
        after:
          - cmd: echo Linux!
```

![image](https://github.com/defenseunicorns/zarf/assets/3977569/6c8f6073-3d33-4f58-904b-7f4b6d92f5a0)
