### ISSUE TITLE
components.scripts.before with retry doesn't cause a fatal if it times out

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#223]
If I have

```yaml
components:
  - name: foo
    scripts:
        retry: true
        before:
          - <SomeCommandThatWaitsUntilIstioIsReady>
```

my intention is to wait to run the component until Istio is ready, but Zarf continues on with processing if the before command times out. I expected it to cause a fatal instead.
