### ISSUE TITLE
Refactor `charts` definition in `zarf.yaml`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2245]
### Describe what should be investigated or refactored
It would be worth taking some time to refactor the `charts` definition in the `zarf.yaml` to enhance user understanding of the keys such as `repoName` and `gitPath` which are usually non-intuitive for users.  `repoName` really means the name of a chart _in_ a Helm Repo and `gitPath` means the path of a chart _in_ a `git` repository which are not obvious to folks not familiar with Zarf.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/blob/f039affe91b664f601b274a5e66d29bf030ca75f/src/types/component.go#L92

### Additional context
These fields have come up with questions a few times in user questions in our `k8s` slack.

**Comment by AustinAbro321** [comment]
propose a schema that looks like below. This is based on the examples/helm-charts within the Zarf repository. Non changed fields were taken out for brevity. Exactly one of the following field will exist for each `components.charts`.

```yaml
- name: podinfo-repo-new
  helmRepo:
    url: https://stefanprodan.github.io/podinfo
    name: podinfo # replaces repoName since it's only applicable for helm chart repositories
    version: 6.4.0

- name: podinfo-git-new
  git:
    url: https://stefanprodan.github.io/podinfo@6.4.0
    path: charts/podinfo
    # no version field, use chart.yaml version field at that git tag

- name: podinfo-oci-new
  oci:
    url: oci://ghcr.io/stefanprodan/charts/podinfo
    version: 6.4.0

- name: podinfo-local-same
  local:
   path: chart
    # no version field, use local chart.yaml version
```
