### ISSUE TITLE
Add a `--why` to `zarf dev find-images` to show the chart and resource that generated the image reference

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2272]
### Is your feature request related to a problem? Please describe.
**As** Ezra **I want** a way to find out how Zarf came to find an image reference **so that** I can more easily track down where this reference came from in my manifests or helm charts.

### Describe the solution you'd like

- **Given** I have a `zarf.yaml` that returns images from `zarf dev find-images`
- **When** I run `zarf dev find-images <path-to-zarf-yaml> --why <image-ref>`
- **Then** Zarf will not return the full image list
- **And** will instead return the name of the first chart and resource that that reference was found within.

i.e.

```bash
zarf dev find-images examples/dos-games/ --why defenseunicorns/zarf-game:multi-tile-dark
```

should return:

**component**: baseline
**manifest**: multi-games
**resource**:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
spec:
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
        - name: multi-game
          image: "defenseunicorns/zarf-game:multi-tile-dark"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "250m"
```

### Describe alternatives you've considered
We could try to dig into the values files ourselves but this would only work for charts and may not be useful in all cases (it also assumes the images are not hardcoded)

### Additional context
Zarf should do its best to highlight the image reference in the templated manifest by changing its color or bolding it.
