### ISSUE TITLE
Actions erroneously return a timeout message when the command did not timeout.

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2299]
### Environment
Device and OS: System76 drap8
App version: v0.32.3
Kubernetes distro being used: any
Other: n/a

### Steps to reproduce
1. Include an action command (like `exit 1`) that will fail right away without configuring maxTotalSeconds or maxRetries.
2. Run the associated Zarf command (i.e. `zarf package create .` for the below `zarf.yaml`):

```yaml
kind: ZarfPackageConfig
metadata:
  name: actions-error-msg

components:
  - name: actions-error-msg
    actions:
      onCreate:
        before:
          - cmd: exit 1
```

### Expected result

An error message like `Failed to create package: unable to add component "actions-error-msg": unable to run component before action: command "exit 1" failed` displays.

### Actual Result

The error message `Failed to create package: unable to add component "actions-error-msg": unable to run component before action: command "exit 1" timed out after 0 seconds` displays.

### Visual Proof (screenshots, videos, text, etc)

![image](https://github.com/defenseunicorns/zarf/assets/3977569/94ad5a3a-6f3d-412f-abab-19a207caf5bc)

### Severity/Priority

Medium

### Additional Context
This causes confusion because people may be misled into believing that Zarf has timed out their command when it was the command that failed instead.
