### ISSUE TITLE
lib: configure `pterm` output during Deploy lifecycle

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#2372]
### Is your feature request related to a problem? Please describe.

In this [branch](https://github.com/defenseunicorns/uds-cli/pull/210) of UDS CLI, we are bringing in BubbleTea as our TUI. For most  Zarf packages, we can configure Zarf with `message.NoProgress = true` and everything looks great

![Screenshot 2024-03-11 at 9 30 24 AM](https://github.com/defenseunicorns/zarf/assets/42304551/fe9bd345-72ba-49af-93f4-95e825b0e0b0)

However, when deploying a package _after_ an `init` pkg we get pterm artifacts showing up in our BubbleTea program

```yaml
kind: UDSBundle
metadata:
  name: test
  version: 0.0.1

packages:
  - name: init
    repository: ghcr.io/defenseunicorns/packages/init
    ref: v0.32.4
    optionalComponents:
      - git-server
  - name: podinfo
    path: "../../packages/podinfo"
    ref: 0.0.1

```

![Screenshot 2024-03-11 at 9 35 07 AM](https://github.com/defenseunicorns/zarf/assets/42304551/e48ad3ef-da1e-44c9-a367-4158ac9e812d)

### Describe the solution you'd like
We'd like to:
- continue to capture Zarf logs in the log file
- not show any pterm output during the BubbleTea program

### Additional Details
Haven't looked too much into it, but it looks like there are instances in the Zarf deploy lifecycle that modify pterm's output: [example](https://github.com/defenseunicorns/zarf/blob/e5cbe4008987e17d487b0ffbdb42ac5f0d2e669c/src/pkg/message/credentials.go#L35)
