### ISSUE TITLE
NginX Ingress Controller - provided digest did not match uploaded content

### ISSUE THREAD

**Issue by FrankWigger** [defenseunicorns/zarf#2394]
### Environment
Device and OS: Debian bookworm
zarf version: v0.32.5
Kubernetes distro being used: from zarf
Other:

### Steps to reproduce
1. Create a zarf.yaml withn ginx ingress controller.
2. Call zarf prepare find-images
3. zarf package create.
4. On target maschine call zarf package deplpy

### Expected result
Nginx ingress is up and running

### Actual Result
Zarf reports
 Retrying (1/3) in 5s: PUT
http://127.0.0.1:34819/v2/ingress-nginx/controller/manifests/sha256:42b3f0e5d0846876b1791cd3afeb5f1cbbe4259d6f35651dcc1b5c980925379c:
          DIGEST_INVALID: provided digest did not match uploaded content

### Zarf.yaml
My zarf.yaml looks like:
```
kind: ZarfPackageConfig # ZarfPackageConfig is the package kind for most normal zarf packages
metadata:
  name: ingress-nginx      
  version: v0.1.2  
  description: |        
    "A Zarf Package that deploys the nginx ingress controller"
components:
  - name: ingress-nginx
    description: |   
      "Deploys nginx ingress controller"
    required: true   
    charts:
      - name: ingress-nginx
        url: https://kubernetes.github.io/ingress-nginx
        version: 4.10.0
        namespace: ingress-nginx
    images:
      - registry.k8s.io/ingress-nginx/controller:v1.10.0@sha256:42b3f0e5d0846876b1791cd3afeb5f1cbbe4259d6f35651dcc1b5c980925379c
      - registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.4.0@sha256:44d1d0e9f19c63f58b380c5fddaca7cf22c7cee564adeff365225a5df5ef3334
      # Cosign artifacts for images - ingress-nginx - ingress-nginx
      - registry.k8s.io/ingress-nginx/controller:sha256-42b3f0e5d0846876b1791cd3afeb5f1cbbe4259d6f35651dcc1b5c980925379c.sig
      - registry.k8s.io/ingress-nginx/kube-webhook-certgen:sha256-44d1d0e9f19c63f58b380c5fddaca7cf22c7cee564adeff365225a5df5ef3334.sig
```

Any ideas?
