### ISSUE TITLE
Add support for Crossplane CRDs

### ISSUE THREAD

**Issue by Avarei** [defenseunicorns/zarf#2572]
### Is your feature request related to a problem? Please describe.
Crossplane reads some image references in its Provider, Function, and Configuration manifests before creating a Deployment.
Since Zarf-Agent does not yet cover these CRDs, crossplane attempts to pull these Images from the Internet.

### Describe the solution you'd like

- **Given** a Crossplane Provider, Configuration, or Function resource
- **When** creating or updating
- **Then** mutate spec.package and add spec.packagePullSecret

### Describe alternatives you've considered
An alternative would be to support arbitrary CRDs but this would be far more complex to implement.

### Additional context
This is a typical Provider resource (Configurations, and Functions look similar):
```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-kubernetes
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.13.0
```
The Crossplane Pod will pull the image referenced in spec.package read some metadata, and create a Deployment for it.

I have already implemented a working prototype and if there is interest from your side I would be happy to finalize it with your feedback.
