### ISSUE TITLE
Allow package creators to sign packages

### ISSUE THREAD

**Issue by mikhailswift** [defenseunicorns/zarf#31]
Zarf packages should be able to be signed by a package creator.  Signing keys could come from GPG, a smart card, X509 key, etc. Signatures can be added in a block to the zarf.yaml.  A zarf package config with signatures could look something like:

```yaml
kind: ZarfPackageConfig
metadata:
  name: appliance-demo-doom
  description: "Demo Zarf appliance mode with doom game"

local:
  manifests: manifests

  images:
    - registry.dso.mil/platform-one/big-bang/apps/product-tools/zarf/game:doom
signatures:
  - keyID: <KEY ID>
    signature: <SIGNATURE>
 ```

`<KEY ID>` is a hash of the signing key's public key and the signature is, obviously, the signature.
Fairly straight forward.  The signature could be of the zarf yaml outside of the signatures block.  If this creates difficulty signatures could exist in a separate file.

These signatures then should be used to verify the package during the `package deploy` stage.

When signed with a key backed by PKI such as a CAC the signature should also be verified against that PKI's CA.
