### ISSUE TITLE
Zarf doesn't consider $KUBECONFIG env when running commands

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#315]
## Summary
Now that Zarf can support deploying onto existing clusters, we should be considering that users local $KUBECONFIG env when determining if there is an existing cluster to deploy onto. Currently, Zarf is hard coded to look for an existing kubeconfig at `~/.kube/config`. This was perfectly fine when Zarf also was responsible for standing up its on k3s cluster but isn't as clear now.

## Steps to reproduce 
`export KUBECONFIG=~/.kube/otherconfig`
`kind create cluster`
`kubectl get pods -A`        -> Returns the pods on the newly created cluster
`zarf init --confirm`           -> Returns an error because it can't find a k8s even though the above kubectl command could

## Expected Behavior
The Zarf CLI should check if the $KUBECONFIG env is set and prioritize using it whenever possible.

**Comment by RothAndrew** [comment]
@YrrepNoj can you try something a little different for me and paste the console results in?

```sh
export KUBECONFIG=~/.kube/otherconfig          # Configure system to talk to cluster A
kubectl get pods -A                                                # Confirm connection to cluster A
kind create cluster                                                  # Create cluster B
echo $KUBECONFIG                                               # See whether kind changed KUBECONFIG
kubectl get pods -A                                                # Confirm connection to cluster B
```

**Comment by YrrepNoj** [comment]
@RothAndrew I think I understand what you're trying to ask. After that stage of commands here is what kubeconfig that lives at $KUBECONFIG looks like.

```
(base) ➜  build git:(315-kubeconfig-env) ✗ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:50685
  name: kind-cluster-a
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:51061
  name: kind-cluster-b
contexts:
- context:
    cluster: kind-cluster-a
    user: kind-cluster-a
  name: kind-cluster-a
- context:
    cluster: kind-cluster-b
    user: kind-cluster-b
  name: kind-cluster-b
current-context: kind-cluster-b
kind: Config
preferences: {}
users:
- name: kind-cluster-a
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: kind-cluster-b
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
