### ISSUE TITLE
Error trying to use Repo1 helm chart

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#328]
When I try to use this `zarf.yaml`:

```yaml
kind: ZarfPackageConfig
metadata:
  name: software-factory
  description: "Zarf deployment of a software factory"
  # Iron Bank doesn't support ARM
  architecture: amd64

components:
  - name: atlassian
    required: true
    secretName: "private-registry"
    charts:
      - name: jira
        url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/jira.git
        version: 0.1.0-bb.7
        namespace: jira
        valuesFiles:
          - values/jira.yaml
      - name: confluence
        url: https://repo1.dso.mil/platform-one/big-bang/apps/third-party/confluence.git
        version: 0.1.0-bb.9
        namespace: confluence
        valuesFiles:
          - values/confluence.yaml
    images:
      # jira
      - registry1.dso.mil/ironbank/atlassian/jira-data-center/jira-node:8.18.1
      # confluence
      - registry1.dso.mil/ironbank/atlassian/confluence-data-center/confluence-node:7.13.0
      - registry1.dso.mil/ironbank/redhat/ubi/ubi7-minimal:7.9
```

I get this error:

![image](https://user-images.githubusercontent.com/16000938/154183924-acb74fcf-8fa3-4284-9c36-51174bd47445.png)

I'm guessing I just don't have the right syntax now when specifying the URL? Before just randomly trying different permutations of ways to reference files and folders in a git repo URL I thought I'd ask...

**Comment by RothAndrew** [comment]
Full example here: https://github.com/defenseunicorns/zarf-package-software-factory/tree/update-compatibility-to-latest-version-of-zarf

**Comment by YrrepNoj** [comment]
There is a `gitPath` value for the  `charts:` to point to where the Chart.yaml lives in the upstream repo. For most (all?) bigbang packages I think the value should be

```
charts:
  - name: ....
     url: ....
     .......
     gitPath: chart
```

[Here's ](https://github.com/defenseunicorns/zarf/blob/master/examples/single-big-bang-package/zarf.yaml)an example in the single-big-bang-package example.
