### ISSUE TITLE
Configurable Script Timeout

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#338]
**Is your feature request related to a problem? Please describe.**
In the big Software Factory package, the Atlassian suite and Jenkins are installed as separate components after Big Bang deploys, but they have to wait until Istio is running or they won't get sidecar injections. I have this in those components, so it will wait for Istio to be running before trying to deploy:

```yaml
    scripts:
      retry: true
      before:
        # Check to see if istiod is running before trying to deploy. If Istio is running then so is Gatekeeper. This is a poor man's version of "DependsOn" since we aren't doing real gitops yet
        - |
          test $(/usr/sbin/kubectl get pods -n istio-system -l app=istiod --field-selector=status.phase=Running -o json | ./jq -r '.items | length') -gt 0
```

The problem is that it can sometimes take a few minutes for Istio to be running and Zarf times it out at ~~2 minutes~~ 60 retries with a 2 second wait between tries which roughly equates to 2 minutes if you don't count actual processing time.

**Describe the solution you'd like**
I'd like the ability to configure the timeout, instead of it being hardcoded to 2 minutes.

**Describe alternatives you've considered**
I'm not really aware of any that would let me do this all in one package, automatically, without doing something super hacky with initcontainers or something.
