### ISSUE TITLE
Zarf package support for non-container binaries

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/zarf#434]
**Is your feature request related to a problem? Please describe.**

I love Zarf, but I need to be able to package non-containerized binaries for deployment across the airgap. For example, in my SatOps environment, I want to upload packages to my on-orbit payload using my 'update' service.

**Describe the solution you'd like**

1) A specification allowing me to include non-container binaries in a zarf package. 
2) A specification for where I can access the binary after an airgap deployment.

**Describe alternatives you've considered**

None considered.

**Additional context**

A strong use case for this exists, when dealing with edge system that have both a Kubernetes cluster/s and non-container software for edge devices.

**Comment by RothAndrew** [comment]
If I'm understanding correctly what I think you are asking, this is already possible. Here's a snippet:

```yaml
kind: ZarfPackageConfig
metadata:
  name: move-a-file-to-the-airgap-and-use-it

components:
  - name: thefile
    files:
      - source: scripts/do-all-the-things.sh
        target: /usr/sbin/do-all-the-things.sh
        executable: true
    scripts:
      after:
        - /usr/sbin/do-all-the-things.sh
```
