### ISSUE TITLE
Kustomize options does not allow to include patches from a different subdirectory

### ISSUE THREAD

**Issue by mahomedalid** [defenseunicorns/zarf#452]
### Environment
Device and OS: Windows WSL
App version: v0.17.0
Kubernetes distro being used: Client v1.22.5 / Server v1.23.4

### Steps to reproduce
1. Having the following structure:

```
root/
├─ applications/
│  ├─ alpha/
│  ├─ beta/
│  ├─ my-system/ManifestDeployments
│  │  ├─ prometheus/
│  │  │  ├─ patches/
│  │  │  │  ├─ labels.yaml
│  │  │  ├─ kustomization.yaml
│  │  │  ├─ namespace.yaml
│  │  │  ├─ release.yaml
│  │  │  ├─ repository.yaml
├─ clusters/
│  ├─ prod/
│  │  ├─ prometheus/
│  │  │  ├─ kustomization.yaml
│  ├─ edge/
├─ zarf.yaml
```

2. The kustomization.yaml inside clusters have a structure similar to:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../../applications/my-system/ManifestDeployments/prometheus
patches:
  - ../../../../../../applications/my-system/ManifestDeployments/prometheus/patches/labels.yaml
```

### Expected result

Patches can be applied to different clusters targets/versions, without need to re-create different kustomization files. Success at packaging the build.

### Actual Result

```
...; file '.../applications/my-system/ManifestDeployments/prometheus/patches/labels.yaml' is not in or below '.../clusters/edge/coral-system/ManifestDeployments/prometheus/all'

ERROR:  unable to build the kustomization for clusters/edge/my-system/ManifestDeployments/prometheus/all
```

### Severity/Priority

TBD

### Additional Context

This restriction was added here https://github.com/kubernetes-sigs/kustomize/pull/995 and here https://github.com/kubernetes-sigs/kustomize/pull/700, but later allowed under certain circumstances here https://github.com/kubernetes-sigs/kustomize/issues/865, which is an option that flux v2 uses.

**Comment by jeff-mccoy** [comment]
Now that I think about it, we do have the ability to bring in [composable components](https://github.com/defenseunicorns/zarf/blob/master/docs/components.md#composing-package-components) that might also serve this function if you had a zarf package sitting in `../../../../../../applications/my-system`, you could import that component now without any code changes.  

Thoughts?

**Comment by mahomedalid** [comment]
That is something we though as well, but I still see it as a workaround than an option. The reason is that in this scenario, the app/clusters manifests could be generated or already exists and will require to remove the patches from every one of the kustomization files in the cluster folder. I see that this issue is not a blocker, but I believe is still necessary. Thoughts @eedorenko?

**Comment by jeff-mccoy** [comment]
So my biggest concern with this approach is right now we try really hard to make it clear what you are packing/deploying via confirmations.  Files can already do paths like you describe, but we tell you explicitly what that path is before create/deploy.  If Kustomize is able to able to bring in other paths, right now Zarf would only indicate the kustomize path, not any bases/resources outside of that folder.  I think we'd need to see this as a non-ideal behavior similar to how we allow but discourage remote package deployments without a shasum specified, we require adding the "insecure" flag.  

However, I also wouldn't want to force a user to add a flag each time they were creating a package that allowed kustomize to fetch files from other paths.  What we could do is add a boolean to the package spec for kustomize to do this behavior.  Then at least the user is agreeing to this when the package is created, e.g. `kustomizePermitAnyDirectory: true`:

```
kind: ZarfPackageConfig
metadata:
  name: flux
  description: "Zarf flux package."
  architecture: amd64

components:
  - name: flux
    required: true
    secretName: "private-registry"
    manifests:
      - name: flux-installer
        kustomizePermitAnyDirectory: true
        # This will be built on the package create side and deployed as a regular manifest on package deploy
        kustomizations:
          - https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux?ref=1.28.0
    images:
      # Flux images
      - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.16.0
      - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.20.0
      - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.21.0
      - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.21.1
```
