### ISSUE TITLE
Add a way to handle dependencies within components of a package

### ISSUE THREAD

**Issue by vyta** [defenseunicorns/zarf#518]
**Is your feature request related to a problem? Please describe.**
Deployments of components may fail if it depends on other components that have not been fully deployed via flux. (For example, an application relying on certain CRD's deployed as part of bigbang, helm install returns successfully so zarf moves onto the next component (app), but flux hasn't deployed everything yet)

**Describe the solution you'd like**
A mechanism to denote dependencies such that zarf can ensure certain resources exist before deployment of a component. Perhaps specifying namespace, deployment name, or a healthcheck/readiness endpoint that zarf can verify

**Comment by RothAndrew** [comment]
This may be best handled in Flux. Flux HelmRelease custom resources allow for a dependency tree natively (see [example](https://github.com/defenseunicorns/zarf-package-software-factory/blob/efe8ef93644d55cac3b924b1dcfffb3e1e0be887/kustomizations/softwarefactoryaddons/base/helmrelease.yaml#L42).

If desired to have a zarf component wait until something is fully ready the `scripts.after` block may be used as well as an alternate solution.

```yaml
components:
  - name: foo
     scripts:
       after:
         # waits until the deployment exists
         - while ! kubectl get deployment gitlab-webservice-default -n gitlab; do sleep 5; done
         # waits for the deployment to be healthy/ready
         - kubectl rollout status deployment/gitlab-webservice-default -n gitlab --watch --timeout=300s
```

**Comment by vyta** [comment]
Was not aware of the script blocks, perhaps I missed it in the docs somewhere?

**Comment by RothAndrew** [comment]
Docs are still rough, so wouldn't fault you for missing it :) They're being worked on right now though.

@YrrepNoj have you by any chance looked yet into what automated tools there might be to document the zarf yaml schema, in a similar way that we automatically document the CLI?

**Comment by YrrepNoj** [comment]
@RothAndrew I have not yet but I imagine there are some tools that would be really useful. I'll spend a little bit of time looking into that.

**Comment by jeff-mccoy** [comment]
We've also had some discussions around basic "ready" tests we could do, but haven't come up the right solution.  For example, having a component wait for a specific deployment to be ready might look like:

```yaml
components:
  - name: foo
     waitFor:
       - deployment: example-deployment
          namespace: example
```
