### ISSUE TITLE
Helm chart deployment fails when git tag doesn't match Helm chart version

### ISSUE THREAD

**Issue by tworcester** [defenseunicorns/zarf#526]
### Environment
Device and OS: RHEL 7.9
App version: 0.19.4
Kubernetes distro being used: v1.17.4
Other:

### Steps to reproduce
Zarf package a helm chart using git url and a tag that **doesn't match** the Chart.yaml

zarf.yaml:
```yaml
kind: ZarfPackageConfig
metadata:
  name: harbor-helm
  description: "harbor-helm zarf bundle"
  architecture: amd64

components:
  - name: baseline
    required: true
    charts:
      - name: harbor-helm
        url: https://<gitlab URL>/charts/harbor-helm.git
        version: 2022.06.16-1  # This is a tag in the gitlab project
        namespace: harbor
    images:
    - registry1.dso.mil/ironbank/opensource/goharbor/chartmuseum:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/harbor-core:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/harbor-db:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/harbor-jobservice:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/harbor-portal:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/harbor-registryctl:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/notary-server:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/notary-signer:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/registry:v2.5.1
    - registry1.dso.mil/ironbank/opensource/goharbor/trivy-adapter:v2.5.1
    - registry1.dso.mil/ironbank/opensource/redis/redis6:6.2.7
```

Chart.yaml:
```yaml
apiVersion: v1
name: harbor
version: 1.4.0-dev
appVersion: dev
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/website/master/static/img/logos/harbor-icon-color.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
maintainers:
- name: Wenkai Yin
  email: yinw@vmware.com
- name: Weiwei He
  email: hweiwei@vmware.com
- name: Shengwen Yu
  email: yshengwen@vmware.com
engine: gotpl
```
### Expected result
`zarf package deploy <package>` Deploys the helm chart and images.
### Actual Result
`zarf package deploy <package> -l trace` output:
```bash
Debug: unable to load chart data: unable to load chart tarball: unable to load helm chart archive: stat /tmp/zarf-291764257/components/baseline/charts/harbor-helm-2022.06.16-1.tgz: no such file or directory`
```

Looking in the directory:
```bash
$ cd /tmp/zarf-291764257/components/baseline/charts/
$ ll
total 52
-rw-rw-r--. 1 tworcester tworcester 52320 Jun 16 14:24 harbor-1.4.0-dev.tgz
```

So when the helm chart is bundled inside it is using the version from the Chart.yaml instead of the tag that I provided in the zarf.yaml.

I believe this is a bug or an additional vetting step that should fail during the package creation phase.

**Comment by jeff-mccoy** [comment]
This probably needs some documentation improvements.  You don't have to use the funky git-based helm chart for Harbor.  That really was done for [Big Bang](https://p1.dso.mil/products/big-bang).  You could do something like this:

```yaml
kind: ZarfPackageConfig
metadata:
  name: helm-example
components:
  - name: harbor
    required: true
    charts:
      - name: harbor
        url: https://helm.goharbor.io
        version: 1.9.1
        namespace: harbor
    images:
      - goharbor/chartmuseum-photon:v2.5.1
      - goharbor/harbor-core:v2.5.1
      - goharbor/harbor-db:v2.5.1
      - goharbor/harbor-jobservice:v2.5.1
      - goharbor/harbor-portal:v2.5.1
      - goharbor/harbor-registryctl:v2.5.1
      - goharbor/notary-server-photon:v2.5.1
      - goharbor/notary-signer-photon:v2.5.1
      - goharbor/redis-photon:v2.5.1
      - goharbor/registry-photon:v2.5.1
      - goharbor/trivy-adapter-photon:v2.5.1
```
