### ISSUE TITLE
Images not being found by 'zarf prepare find-images'

### ISSUE THREAD

**Issue by TheFutonEng** [defenseunicorns/zarf#585]
### Environment
Device and OS: Mac
App version: v0.19.4
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. Try to find images in the [Istio Control Plane repo on Repo1](https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane/-/tree/main/)

### Expected result
Images are found

### Actual Result
No images are returned

### Visual Proof (screenshots, videos, text, etc)
```
[rmengert@Robs-MacBook-Pro:~/projects/hncd_demo_7-5/zarf-pkg-vultron-demo]
$ zarf prepare find-images -p /chart
  ✔  Processing helm chart https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git@1.13.2-bb.1                                                                                 
  ✔  Templating helm chart dummy                                                                                                                                                                    
[rmengert@Robs-MacBook-Pro:~/projects/hncd_demo_7-5/zarf-pkg-vultron-demo]
$ 
```

### Severity/Priority
Minor I guess?

### Additional Context
The Istio Control Plane values file does not have images at the root layer of the file.  

One image can be found at {{ [.Values.cni.image](https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane/-/blob/main/chart/values.yaml#L168) }} and another at {{ [.Values.postInstallHook](https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane/-/blob/main/chart/values.yaml#L213) }}.  Not sure if this is the nature of the bug or just because these images have weird keys associated with them.

**Comment by jeff-mccoy** [comment]
Could you share the zarf package yaml or one that reproduces this?  The way that Zarf seeks out images is by first trying to helm template + run manifests / kustomizations through the K8s API to find actual image refs in a `podspec`, it then does a flat text fuzzy search to try and find additional "OCI path-like images": ``(?mi)"([a-z0-9\-./]+:[\w][\w.\-]{0,127})"`` and then tests matches to see if they are actual image paths.

**Comment by TheFutonEng** [comment]
@jeff-mccoy, surely see below.

```
kind: ZarfPackageConfig
metadata:
  name: big-bang-core-demo
  description: "Deploy Big Bang Core - HNCD"
  # Big Bang / Iron Bank are only amd64
  architecture: amd64

components:
  # - name: flux
  #   required: true
  #   manifests:
  #     - name: flux-installer
  #       kustomizations:
  #         - https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux?ref=1.36.0

  #   images:
  #     - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.21.0
  #     - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.25.0
  #     - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.23.5
  #     - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.24.4

  - name: bigbang
    description: "Git repositories and OCI images used by Big Bang Core"
    required: true
    repos:
      # - https://repo1.dso.mil/platform-one/big-bang/bigbang.git@1.36.0
      - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git@1.13.2-bb.1
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git@1.13.2-bb.1
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/jaeger.git@2.30.0-bb.2
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/kiali.git@1.51.0-bb.0
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/cluster-auditor.git@1.4.0-bb.4
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/policy.git@3.8.1-bb.0
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/monitoring.git@35.2.0-bb.3
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana.git@0.7.1-bb.0
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/eck-operator.git@2.0.0-bb.2
      # - https://repo1.dso.mil/platform-one/big-bang/apps/core/fluentbit.git@0.20.0-bb.1
    images:
      - registry1.dso.mil/ironbank/big-bang/grafana/grafana-plugins:8.6.2
      - registry1.dso.mil/ironbank/bigbang/cluster-auditor/opa-exporter:v0.0.4
      - registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:2.0.0
      - registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:7.17.1
      - registry1.dso.mil/ironbank/elastic/kibana/kibana:7.17.1
      - registry1.dso.mil/ironbank/kiwigrid/k8s-sidecar:1.18.0
      - registry1.dso.mil/ironbank/opensource/fluent/fluent-bit:1.9.3
      - registry1.dso.mil/ironbank/opensource/istio/operator:1.13.2
      - registry1.dso.mil/ironbank/opensource/jaegertracing/all-in-one:1.33.0
      - registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-collector:1.33.0
      - registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-operator:1.33.0
      - registry1.dso.mil/ironbank/opensource/jaegertracing/jaeger-query:1.33.0
      - registry1.dso.mil/ironbank/opensource/kiali/kiali-operator:v1.51.0
      - registry1.dso.mil/ironbank/opensource/kubernetes/kube-state-metrics:v2.4.2
      - registry1.dso.mil/ironbank/opensource/openpolicyagent/gatekeeper:v3.8.1
      - registry1.dso.mil/ironbank/opensource/prometheus-operator/prometheus-operator:v0.56.2
      - registry1.dso.mil/ironbank/opensource/prometheus/alertmanager:v0.24.0
      - registry1.dso.mil/ironbank/opensource/prometheus/node-exporter:v1.3.1
      - registry1.dso.mil/ironbank/opensource/prometheus/prometheus:v2.35.0
    manifests:
      - name: big-bang-config
        kustomizations:
          - "kustomization/bigbang"
```

Please let me know if you need anything else!  This is Rob M by the way.
