### ISSUE TITLE
Add `only` filter to zarf components

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#593]
Need to implement a filter for components based off of the cluster architecture and local operating system.  

- [ ] On `package create` filter out components with non-matching architectures 
- [ ] Always include components with OS filters, we will not know what the target runtime OS
- [ ] On `package deploy` filter by OS, matching the current runtime OS

Discussed with @RothAndrew, @YrrepNoj , @brianrexrode and @lucasrod16 to confirm the final structure below:

```yaml
components:
  - name: k3s
    only:
      localOS: linux
      cluster:
        architecture: amd64
```
