### ISSUE TITLE
Variable all the things!

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#613]
Move component-level variables to the package level and allow package string-templating for the Zarf.yaml and package variables templated out manifests.

### Zarf.yaml string templating
- [x] Validation must require uppercase and snake case
- [x] special type of string replace that can only be specified during `package create`
- [x] do not appear in the `variables` or `constants` lists
- [x] can only template string values in a `zarf.yaml`
- [x] run after component composition so cannot change component import paths or names
- [x] check for all matching variables and error if one is not set by the user on `package create`

```yaml
components:
  - name: zarf-agent
    required: true
    images:
      - "###ZARF_VAR_AGENT_IMAGE###"
    manifests:
      - name: zarf-agent
        namespace: zarf
```

### Constant declaration by package authors
- [x] validation must require uppercase and snake case for all variables
- [x] specified as an array under the `constants` key
- [x] only set during `package create`
- [x] cannot be overriden during `package deploy`
- [x] are used with `ZARF_CONST` prefix

```yaml
constants:
  # Must be all-caps, snake-case
  - name: AGENT_IMAGE
    value: "defenseunicorns/zarf-agent:v0.19.5"
```
In the manifest will appear as `###ZARF_CONST_AGENT_IMAGE###`

### Variable declaration by package deployers
- [x] validation must require uppercase and snake case for all variables
- [x] specified as an array under the `variables` key
- [x] set via `default` key
- [x] set via`--set` flags on `package deploy`
- [x] user prompt on `package deploy` if `prompt: true`
- [x] are used with `ZARF_VAR_` prefix

```yaml
variables:
  # Must be all-caps, snake-case
  - name: AGENT_IMAGE
    default: "defenseunicorns/zarf-agent:v0.19.5"

  # This variable will template manifests on deploy and will prompt if the user doesn't specify by flag
  - name: PROMPT_ON_DEPLOY
    prompt: true
```
In the manifest will appear as `###ZARF_VAR_AGENT_IMAGE###` and `###ZARF_VAR_PROMPT_ON_DEPLOY###`

Issue planning coordinated with @RothAndrew @YrrepNoj @Racer159
