### ISSUE TITLE
Expanding Zarf Features to regular zarf packages

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#64]
### Discussed in https://github.com/defenseunicorns/zarf/discussions/63

<div type='discussions-op-text'>

<sup>Originally posted by **jeff-mccoy** September 24, 2021</sup>
Currently only `zarf-init` has the ability to deploy what is in the zarf package and optional additional groups of assets called features.  Providing this capability to regular zarf packages as well wouldn't be difficult, but would allow greater flexibility with package creation.  The only issue would be needing to resolve the use of `local` vs `remote` in the zarf config, https://github.com/defenseunicorns/zarf/discussions/40#discussioncomment-1381213.

Example usage in [zarf init yaml](https://github.com/defenseunicorns/zarf/blob/master/zarf.yaml)
```yaml
features:
  - name: management
    description: "Add the K9s terminal-based K8s UI for cluster management"
    default: true
    files:
      - source: https://zarf-public.s3-us-gov-west-1.amazonaws.com/k9s_Linux_x86_64_v0_24_11
        shasum: 18a5a33bbf58cb228e56a03380dcb6b9bb8624acab4ff63deb7364dc15d3c03f
        target: "/usr/local/bin/k9s"
        executable: true
      - source: assets/misc/k9s-theme.yaml
        target: "/root/.k9s/skin.yml"
```

How this would look for an example package, [tiny-kafka](https://github.com/defenseunicorns/zarf/blob/master/examples/tiny-kafka/zarf.yaml)
```yaml
kind: ZarfPackageConfig
metadata:
  name: kafka-strimzi-demo
  description: "Demo tiny Zarf Kafka deployment"
  
local:
  manifests: manifests

  charts:
    - name: strimzi-kafka-operator
      url: https://strimzi.io/charts/
      version: 0.24.0

  images:
    - registry1.dso.mil/ironbank/opensource/strimzi/operator:0.24.0
    - registry1.dso.mil/ironbank/opensource/strimzi/kafka:0.24.0-kafka-2.8.0

features:
  - name: kafka-tools
    description: "Add useful tools to manage Kafka"
    default: true
    files:
      # Helper tools for working with kafka
      - source: https://archive.apache.org/dist/kafka/2.8.0/kafka_2.13-2.8.0.tgz
        shasum: 3fa380ae5d1385111ee9c83b0d1806172924ffec2e29399fd1a42671a97492c6
        target: /opt/kafka.tgz
```</div>
