### ISSUE TITLE
Load package variables from a file

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#675]
**Is your feature request related to a problem? Please describe.**
For Zarf package variables it would be nice to load them from a file so that you can override many of them at once without needing to manually type them or specify `--set` on the command line (which may be captured in shell history)

**Describe the solution you'd like**
It would be nice to specify a variable override potentially to values.yaml overrides (or similar) in helm.

**Describe alternatives you've considered**
Considered loading from env vars but this would make things more complicated for end users to set the env vars first (rather than simply point to a file)

**Comment by RothAndrew** [comment]
Huge +1 from me on this one. Since it will likely have several hundred deploy-time variables available, DI2-ME will need this before it is able to transition to a model of being able to deploy a pre-built artifact, vice users forking the project and building the package themselves.

**Comment by Racer159** [comment]
After discussion planning to introduce a new `kind` of yaml called a `ZarfOverrideConfig` that has the following structure:

```
kind: ZarfOverrideConfig
metadata:
  # This must match the name of the package being deployed
  name: "init-package-zarf-registry"
  # Optional thingybobber to describe it or something
  description: "Used to establish a new Zarf cluster"
  
# This will use the same shape as a constant vs variable
variables:
  - name: THING_ONE
    value: foo

  - name: THING_TWO
    value: bar
``` 

These could be specified in an array like the following:

`zarf package deploy package-name.zst --set-file override.yaml --set-file override2.yaml`

Extra details:

- There should be a command to generate an example override file
- Override file names must match the package they are overriding

**Comment by jeff-mccoy** [comment]
![image](https://user-images.githubusercontent.com/882485/186237982-2374fbe4-7daf-43f5-b97a-b62af25e3293.png)

**Comment by Racer159** [comment]
Potentially break off into a separate PR to do the following:
- Allow 0-9 (numbers) in variable names
- Add a `description` key to variables and constants

**Comment by Racer159** [comment]
Also considering a breaking change around default handling:
```
variables:
  - name: "WOLF"
    # default: nil <- with a pointer
    # prompt: false <- currently under the hood
  - name: "DOG"
    default: "woof"
    # prompt: false <- currently under the hood
  - name: "CAT"
    # default: nil <- with a pointer
    prompt: true
  - name: "FOX"
    default: "###ZARF_PKG_VAR_CONFIG_MAP###"
    prompt: true
```
---
```
    zarf package deploy package.zst --confirm --set CAT=hello --set FOX=world --set WOLF=hello # works
    zarf package deploy package.zst --confirm --set CAT=hello --set WOLF=hello # works
    zarf package deploy package.zst --confirm --set CAT=hello # does not work
    # Error: Variable WOLF does not have a default, you must specify it with `--set`
    zarf package deploy package.zst --confirm # does not work
    # Error: Variable WOLF does not have a default, you must specify it with `--set`
```
