### ISSUE TITLE
Big Bang Core Example Kubescape Link Incorrect

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#72]
The remote link for the kubescape binary seems to be mutable therefore invalidating the SHA256 hash.

<img width="2091" alt="Screen Shot 2021-09-30 at 2 05 17 AM" src="https://user-images.githubusercontent.com/882485/135404400-58a591aa-f885-48d9-a76b-22828430c70f.png">

**Comment by RothAndrew** [comment]
Dang. Thats annoying. Lets put it in S3 then like we do for k9s.

I've noticed a couple things about kubescape actually that I'm not wild about. Makes me kinda want to fork it and do it better than they are.

**Comment by jeff-mccoy** [comment]
https://github.com/defenseunicorns/zarf/pull/71/commits/1b7a3935d74598466b5d1ae0e236ef514779abcc

**Comment by jeff-mccoy** [comment]
Here's the updated values, but want to wait until #71 is in to avoid more merge conflict fun:  

```yaml
    files:
      - source: https://zarf-public.s3-us-gov-west-1.amazonaws.com/kubescape
        shasum: 2754848328ce4ca288c8d03bb66a04ada08e326f6621195d28af903ae9d15884
        target: "/usr/local/bin/kubescape"
        executable: true
      - source: https://zarf-public.s3-us-gov-west-1.amazonaws.com/kubescape-nsa
        shasum: 25b6dda6ce2ad36bf6a4ea8d1e0ef0c6bda73f9111f4c0d71f260c36a16c6498
        target: "/usr/local/bin/kubescape-framework-nsa.json"
```
