### ISSUE TITLE
Unable to pull Bitnami charts

### ISSUE THREAD

**Issue by NunoSav** [defenseunicorns/zarf#740]
### Environment
Device and OS: macOS 12.6
App version: v0.21.3
Kubernetes distro being used: k3s
Other:

### Steps to reproduce
1. Zarf Package yaml content:
```yaml
kind: ZarfPackageConfig
metadata:
  name: "chirpstack-v3"
  description: "Zarf ChirpStack version 3 package."
  version: "0.0.1"
components:
  - name: chirpstack-component
    required: true
    charts:
      - name: mosquitto
        url: https://k8s-at-home.com/charts/
        version: 4.8.2
        namespace: chirpstack
        valuesFiles:
          - mosquitto/config.yaml
      - name: bitnami/redis
        releaseName: redis
        url: https://charts.bitnami.com/bitnami
        version: 17.1.6
        namespace: chirpstack
        valuesFiles:
          - redis/config.yaml
      - name: postgresql
        releaseName: postgresql
        url: https://charts.bitnami.com/bitnami
        version: 11.9.1
        namespace: chirpstack
        valuesFiles:
          - postgres/config.yaml
    images:
      - chirpstack/chirpstack-application-server:3.17
      - chirpstack/chirpstack-network-server:3.16
      - chirpstack/chirpstack-gateway-bridge:3.14
      - eclipse-mosquitto:2.0.14
      - postgres:14.5
      - redis:7.0.4
```

### Expected result
`zarf package create ...` would be successful

### Actual Result
Zarf can't pull bitnami charts

### Visual Proof (screenshots, videos, text, etc)
<img width="631" alt="Screenshot 2022-09-16 at 17 42 41" src="https://user-images.githubusercontent.com/26490343/190688433-89a07877-6a35-4c5e-bdb0-a81f1611af7c.png">
