### ISSUE TITLE
Composable Packages from a URL

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/zarf#823]
**Describe the solution you'd like**
I'd like to build a Zarf package referencing a package via URL.

```
  - name: games
    description: "Games package"
    import:
      path: https://raw.githubusercontent.com/defenseunicorns/zarf/master/examples/game/
...
```

**Additional context**
Short slack discussion [here](https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1664653708490319)
