### ISSUE TITLE
Add capability to add a helm chart from local files

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#836]
Currently the only way to include a helm chart is from a git repo or a remote helm repo, this introduces problems for helm charts that either aren't published or are published in private settings. This especially introduces complexity when trying to create a zarf package from a helm chart in a project's CI/CD pipeline where they both exist in the same repo. Proposed yaml below:
```yaml
components:
  - name: localChartComponent
    charts:
      - name: localChart
        version: 0.1
        namespace: default
        localPath: /path/to/chart/folder/
```
