### ISSUE TITLE
Ability to add labels to Zarf-generated namespaces

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#914]
**Is your feature request related to a problem? Please describe.**
I'm building a small Zarf package that is designed to be deployed to a cluster that is running Istio, but AFAIK I don't have a way to apply the `istio-injection: enabled` label to the namespace that Zarf generates unless I generate the namespace myself.

**Describe the solution you'd like**
I'd like the ability to tell Zarf to apply labels to namespaces that it generates, using perhaps something like this:

```yaml
components:
  - name: foo
    description: "Foo component" 
    required: true
    manifests:
      - name: foo
        namespace: foo
        namespaceLabels:
          istio-injection: enabled
        files:
          - manifests.yaml
```

or perhaps something like this rather than `namespaceLabels` which feels a little weird:

```yaml
namespace:
  name: foo
  labels:
    istio-injection: enabled
```

**Describe alternatives you've considered**
Creating the namespace myself in the manifests that are being applied, which is fine as a workaround, but a little cludgy
